### ISSUE TITLE
Remove vestiges of PHP

### ISSUE THREAD

**Issue by melange396** [cmu-delphi/delphi-epidata#1001]
Remove the PHP files that are no longer in use, as well as other associated files.

_**This is not to be confused with the "php" alias endpoint, which exists for backwards compatibility reasons and should not be removed.**_  It is often referred to as `'http://delphi_web_epidata/epidata/api.php'` or `'https://delphi.cmu.edu/epidata/api.php'` or simply even `/api.php` in the source code.

- The files `./src/server/*.php` are part of an older version of the API web server and have since been superseded.

- The files `./src/acquisition/*/*.php` should probably go too, but i am unsure of their function.

- Some dev guide documentation still includes references to PHP files and services which should be updated (found locally in `./docs/epidata_development.md` along with similar files in the `operations` repository)

- The files in `./dev/docker/web/*` help define a docker image to run the old PHP service (it builds upon the base image definition in the `operations` repo, found [here](https://github.com/cmu-delphi/operations/blob/main/dev/docker/web/Dockerfile)).  The `./dev/docker/web/` directory can be removed, or it can be emptied and the docker definition from `./devops/*` could be relocated there.  This is related to [[#1000]] and [[#965]]

**Comment by BrainIsDead** [comment]
@melange396  there are `cdc_upload.php`, `dasboard.php` and `master.php` in `./src/acquisition/*/*`:
*  `cdc_upload.php` meets once in `/delphi-epidata/deploy.json`
* `dashboard.php` should be available by the link `https://delphi.cmu.edu/~automation/public/wiki/` but it returns 404 for me, also meets in `/delphi-epidata/deploy.json` 
* `master.php` is for rearing `wiki_raw` table independently and in parallel to `wiki_download.py`,  and looks loke exists in `wiki_download` as `MASTER_URL = 'https://delphi.cmu.edu/~automation/public/wiki/master.php'` (but link returns 404 for me). Also meets in `/delphi-epidata/deploy.json` 

Not sure what I should to do with these files
