### ISSUE TITLE
`/csv` endpoint serves only `jhu-incidence` data

### ISSUE THREAD

**Issue by dshemetov** [cmu-delphi/delphi-epidata#1005]
Want to confirm if this is the intended use case for this endpoint or if this is a bug. I can't find documentation for this endpoint in the [API docs](https://cmu-delphi.github.io/delphi-epidata/). 

https://github.com/cmu-delphi/delphi-epidata/blob/bef5839744086eec21081cc86ec2b056fe00658f/src/server/endpoints/covidcast.py#L350-L354

**Comment by krivard** [comment]
OH NO

excellent catch

we should check if [https://delphi.cmu.edu/covidcast/export/](https://delphi.cmu.edu/covidcast/export/) uses /csv or something else. if it uses /csv... well then it's just been broken for a year+ and nobody told us 😮

**Comment by dshemetov** [comment]
I tried two different signals from Change and from Doctor's Visits and it gave me two different files 🙏, so it must be using something else.

**Comment by krivard** [comment]
Ohhh that's just a default if you don't specify the source/signal

**Comment by dshemetov** [comment]
Whoops, sorry for the panic
