### ISSUE TITLE
Update CI for Node 12

### ISSUE THREAD

**Issue by krivard** [cmu-delphi/delphi-epidata#1032]
We're getting these messages in builds:

> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout@v2

**Comment by melange396** [comment]
duplicated by #1162 , fixed by #1269
