### ISSUE TITLE
Update CI for set-output and save-state

### ISSUE THREAD

**Issue by krivard** [cmu-delphi/delphi-epidata#1033]
We're generating these messages in builds:

> The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

> The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by melange396** [comment]
duplicate of #1015
