### ISSUE TITLE
make a "src/common/" directory (package?) to share between server and acquisition code

### ISSUE THREAD

**Issue by melange396** [cmu-delphi/delphi-epidata#1037]
to promote modularity and reduce code repetition, we should create a "`./src/common/`" directory (and potentially package too).  this will require some changes to our docker definitions and maybe also other parts of our build process.

the first file/module to include here could be our structured logger code...  see: https://github.com/cmu-delphi/delphi-epidata/pull/1027#discussion_r1022131246_

**Comment by melange396** [comment]
following up, these two files are now essentially identical:
[./src/acquisition/covidcast/logger.py](https://github.com/cmu-delphi/delphi-epidata/blob/dev/src/acquisition/covidcast/logger.py)
[./src/server/utils/logger.py](https://github.com/cmu-delphi/delphi-epidata/blob/dev/src/server/utils/logger.py)

**Comment by krivard** [comment]
& the third one:
[covidcast-indicators/_delphi_utils_python/delphi_utils/logger.py](https://github.com/cmu-delphi/covidcast-indicators/blob/main/_delphi_utils_python/delphi_utils/logger.py)

**Comment by melange396** [comment]
a big part of the problem is that the server code cant "see" the acqusisition code but the acq can see the server.

the root of this lies in two different docker setups:
  - [these files](https://github.com/cmu-delphi/delphi-epidata/tree/dev/dev/docker/python) preserve the module structure for the `delphi_web_python` docker image: all of the code tree is visible and happy.
  - [this definition](https://github.com/cmu-delphi/delphi-epidata/blob/dev/devops/Dockerfile) for the `delphi_web_epidata` image keeps only `src/server/` code: the non-server code gets chopped out completely.


fixing the server docker image might (almost) be as simple as something like this...
change [this line](https://github.com/cmu-delphi/delphi-epidata/blob/9ab7840577c7cf1752cc3b47c495f0e9a4125669/devops/Dockerfile#L11) to something like:
```
  RUN mkdir -p /app/delphi/epidata
  COPY ./src/* /app/delphi/epidata/
```
or perhaps just:
```
  RUN mkdir -p /app/delphi/epidata
  COPY ./src/server /app/delphi/epidata/
  COPY ./src/common /app/delphi/epidata/
```
then use environment variables `$MODULE_NAME` + `$VARIABLE_NAME` (or just `$APP_MODULE`) to run `delphi.epidata.server.main:app` as described [here](https://github.com/tiangolo/meinheld-gunicorn-docker#module_name).  (those env variables would need to be added to our dev [Makefile](https://github.com/cmu-delphi/delphi-epidata/blob/9ab7840577c7cf1752cc3b47c495f0e9a4125669/dev/local/Makefile#L80), the github [ci.yaml](https://github.com/cmu-delphi/delphi-epidata/blob/9ab7840577c7cf1752cc3b47c495f0e9a4125669/.github/workflows/ci.yaml#L64), and probably somewhere in our scheduler/automation system).

a nice bonus is that i think this will also let us turn all of the relative local imports in the server code into fully qualified ones.

**Comment by melange396** [comment]
in addition to the logging module[s] mentioned above, the newly extracted `CovidcastRow` (see #1044) is another great first candidates to go in the `common/` tree.  after that, we could pull stuff from `src/server/utils/*` , and probbly some of `src/server/endpoints/covidcast_utils/*`

**Comment by melange396** [comment]
this will probably also need to include some changes to `deploy.json`, similar to those recently seen in https://github.com/cmu-delphi/delphi-epidata/pull/1097
