### ISSUE TITLE
Add covid_naat_pct_positive_7dav to the dsew documentation

### ISSUE THREAD

**Issue by krivard** [cmu-delphi/delphi-epidata#1052]
We've apparently been merrily serving test positivity data from the DSEW Community Profile Report without telling anyone what it is or what it means. We should add an entry to the signal table for `covid_naat_pct_positive_7dav`.

* [Source file](https://github.com/cmu-delphi/delphi-epidata/blob/dev/docs/api/covidcast-signals/dsew-cpr.md)
* [Rendered file](https://cmu-delphi.github.io/delphi-epidata/api/covidcast-signals/dsew-cpr.html)
* [Indicator source](https://github.com/cmu-delphi/covidcast-indicators/tree/main/dsew_community_profile)

**Comment by nmdefries** [comment]
Added to signal spreadsheet. Added to documentation site in https://github.com/cmu-delphi/delphi-epidata/pull/1404.
