### ISSUE TITLE
Info on the covidcast `consensus` signal

### ISSUE THREAD

**Issue by noamross** [cmu-delphi/delphi-epidata#106]
Hello, thanks for all your work here.  I was wondering if there is information on the source and nature of the `consensus` data source and signals in the COVIDcast API.  I haven't found it anything across any of the repos and websites.

**Comment by capnrefsmmat** [comment]
Sorry nobody got back to you -- we haven't been watching this repo closely enough.

The consensus data source is gone, replaced with `indicator-combination`, which is [documented here](https://cmu-delphi.github.io/delphi-epidata/api/covidcast_signals.html). More details on the statistical approach will be posted within a few weeks. But if you have specific questions about it, I can point you to the right people to ask.
