### ISSUE TITLE
Add basic integration tests for all endpoints

### ISSUE THREAD

**Issue by rzats** [cmu-delphi/delphi-epidata#1068]
This PR https://github.com/cmu-delphi/delphi-epidata/pull/1062 had some endpoints with missing imports, but passed integration testing. We should make sure all endpoints are covered by basic integration tests ("doesn't throw an error") to prevent this from happening.

Missing imports were fixed in https://github.com/cmu-delphi/delphi-epidata/pull/1067.

Starter list of endpoints:
- [ ] ~afhsb~ (table doesn't exist; #1141 to remove)
- [x] cdc
- [x] covid_hosp_facility
- [x] covid_hosp_facility_lookup
- [x] covid_hosp_state_timeseries
- [x] covidcast
- [x] covidcast/meta
- [x] TODO: list additional covidcast/ endpoints from [covidcast.py](https://github.com/cmu-delphi/delphi-epidata/blob/dev/src/server/endpoints/covidcast.py)
- [x] covidcast_meta (different from covidcast/meta)
- [x] covidcast_nowcast
- [x] delphi
- [x] dengue_nowcast
- [x] dengue_sensors
- [x] ecdc_ili
- [x] flusurv
- [x] fluview
- [x] fluview_clinical
- [x] fluview_meta
- [x] gft
- [x] ght
- [ ] ~ilinet~ (replaced with fluview)
- [x] kcdc_ili
- [x] meta
- [ ] ~meta_afhsb~ (table doesn't exist; #1141 to remove)
- [x] meta_norostat
- [x] nidss_dengue
- [x] nidss_flu
- [x] norostat
- [x] nowcast
- [x] paho_dengue
- [x] quidel
- [x] sensors
- [x] signal_dashboard_coverage
- [x] signal_dashboard_status
- [x] twitter
- [x] wiki

For each we need to:
1. see if it has coverage in integration tests
2. if so, check it off
3. if not, add a test, then check it off

**Comment by melange396** [comment]
possibly helpful: Dmitry "dug through the old endpoints and got one non-trivial response query for almost all of them" ([slack message](https://delphi-org.slack.com/archives/C02U0AX8KJR/p1681765116044499?thread_ts=1681755927.755679&cid=C02U0AX8KJR))

**Comment by melange396** [comment]
done in #1241
