### ISSUE TITLE
Some NoroSTAT DB table creation queries are in wrong function

### ISSUE THREAD

**Issue by brookslogan** [cmu-delphi/delphi-epidata#1098]
The `CREATE TABLE IF NOT EXISTS` [commands](https://github.com/cmu-delphi/delphi-epidata/blob/510e31f59adf08fd93e37f478a035a9b3abed738/src/acquisition/norostat/norostat_sql.py#L350) for `norostat_point_{list,diffs}` are at the end of the `record_long_raw`.  They could be moved either to `ensure_tables_exist`, or to a new function `ensure_point_tables_exist` that should be called [immediately before `update_point`](https://github.com/cmu-delphi/delphi-epidata/blob/510e31f59adf08fd93e37f478a035a9b3abed738/src/acquisition/norostat/norostat_update.py#L25), or to the beginning of `update_point`.

Lower priority than #382, but could be addressed at the same time.

**Comment by melange396** [comment]
these table creation statements no longer exist, see #1207
