### ISSUE TITLE
`covidcast` endpoint - `as_of` field fails silently when given a range of dates

### ISSUE THREAD

**Issue by dshemetov** [cmu-delphi/delphi-epidata#1152]
Giving `as_of` a date range fails silently and it returns the latest data. Example:
https://delphi.cmu.edu/epidata//covidcast/?data_source=hhs&signals=confirmed_admissions_influenza_1d_prop_7dav&time_type=day&geo_type=state&time_values=%2A&geo_values=ca&as_of=20230101-20230102

Giving a single date gives different issues
https://delphi.cmu.edu/epidata//covidcast/?data_source=hhs&signals=confirmed_admissions_influenza_1d_prop_7dav&time_type=day&geo_type=state&time_values=%2A&geo_values=ca&as_of=20230102

Giving it a list of dates, it fails with a helpful error message:
https://delphi.cmu.edu/epidata//covidcast/?data_source=hhs&signals=confirmed_admissions_influenza_1d_prop_7dav&time_type=day&geo_type=state&time_values=%2A&geo_values=ca&as_of=20230101,20230102

[edit from katie:] The behavior we want is for it to fail with a helpful error message.

**Comment by dmytrotsko** [comment]
This happens, because time range like this -> 20230101-20230102 is a "valid range".
This function is used to parse it:
```def parse_date(s: str) -> int:
    # parses a given string in format YYYYMMDD or YYYY-MM-DD to a number in the form YYYYMMDD
    try:
        if s == "*":
            return s
        else:
            return int(s.replace("-", ""))
    except ValueError:
        raise ValidationFailedException(f"not a valid date: {s}")
```
Which means that `20230101-20230102` is parsed to `2023010120230102`.
