### ISSUE TITLE
`covidcast` endpoint - inconsistent handling of ISO format dates

### ISSUE THREAD

**Issue by dshemetov** [cmu-delphi/delphi-epidata#1153]
A list of ISO-format dates is ok:
https://delphi.cmu.edu/epidata//covidcast/?data_source=hhs&signals=confirmed_admissions_influenza_1d_prop_7dav&time_type=day&geo_type=state&time_values=2021-01-01,2021-01-02&geo_values=ca

But a range is not:
https://delphi.cmu.edu/epidata//covidcast/?data_source=hhs&signals=confirmed_admissions_influenza_1d_prop_7dav&time_type=day&geo_type=state&time_values=2021-01-01-2021-01-02&geo_values=ca

**Comment by krivard** [comment]
The ISO format for ranges is `YYYY-MM-DD--YYYY-MM-DD` (two dashes) which in theory we should accept but it looks like that is also not working, e.g.

https://delphi.cmu.edu/epidata//covidcast/?data_source=hhs&signals=confirmed_admissions_influenza_1d_prop_7dav&time_type=day&geo_type=state&time_values=2021-01-02--2021-01-02&geo_values=ca

vs

https://delphi.cmu.edu/epidata//covidcast/?data_source=hhs&signals=confirmed_admissions_influenza_1d_prop_7dav&time_type=day&geo_type=state&time_values=20210102-20210102&geo_values=ca

- [ ] We should return an error message if someone attempts an ISO range with only one dash
- [ ] We should handle ISO ranges the same way as YYYYMMDD ranges

**Comment by melange396** [comment]
> The ISO format for ranges is `YYYY-MM-DD--YYYY-MM-DD` (two dashes) which in theory we should accept

Indeed, [this](https://github.com/cmu-delphi/delphi-epidata/blob/31eed173428787f9c4699c3bbc1619d8cd1a8da3/src/server/_params.py#L221-L226) is supposed to handle that ISO range format, but is either malfunctioning or is not in the processing chain for the time_values argument on that endpoint.

**Comment by dmytrotsko** [comment]
[PR with fix](https://github.com/cmu-delphi/delphi-epidata/pull/1284)
