### ISSUE TITLE
Norostat returning -2 no results despite the table having content

### ISSUE THREAD

**Issue by dsweber2** [cmu-delphi/delphi-epidata#1170]
Initially ran into this here: https://github.com/cmu-delphi/epidatr/pull/102.
`https://api.delphi.cmu.edu/epidata/norostat/?auth=yourAuth&epiweeks=201233&location=1` gives a -2, even though the following works on the (staging) server directly

```mysql
mysql> USE epidata
mysql> SELECT * FROM norostat_point_diffs LIMIT 10;
```

**Comment by melange396** [comment]
the "`1`" you saw in the database is a `location_id` -- a pointer to a location and not a location itself.  the norostat endpoint makes a much more convoluted query than just a SELECT from that table you mentioned.  change your API request from `location=1` to `location=Minnesota%2C%20Ohio%2C%20Oregon%2C%20Tennessee%2C%20and%20Wisconsin` and you'll get a result.

**Comment by dsweber2** [comment]
Got it thanks, I guess this may have implications for the way we call this in the clients
