### ISSUE TITLE
Help! I got an error that says I need to register for an API key. What do I do?

### ISSUE THREAD

**Issue by krivard** [cmu-delphi/delphi-epidata#1183]
In order to better manage server resources and understand our user base, Delphi is limiting anonymous access, and making unlimited access available after registering for an API key. For policy and usage details, consult the [Epidata API keys documentation](https://cmu-delphi.github.io/delphi-epidata/api/api_keys.html). The API will begin accepting keys on 2023-05-24. Anonymous requests that exceed the new limits will be served with increasingly annoying reminder messages from then until 2023-06-21, at which point the API will begin rejecting such requests. If your system has trouble with the reminder messages and you need a key urgently, see below for a temporary key which is available to everyone for the duration of the rollout period.

You can continue to use the API anonymously without providing us with any additional information, even beyond 2023-06-21. However, anonymous requests will soon be limited to public datasets at no more than 60 requests per hour with a maximum of two of the requested parameters having multiple selections (signals, dates, versions, regions, etc).  The rate limit or other restrictions on anonymous access may be subsequently changed as we learn more about their impact.

To access the API without these limits, [register with us for an API key](https://api.delphi.cmu.edu/epidata/admin/registration_form). We are requiring registration for higher-traffic users so that we have someone to contact if usage becomes excessive, abnormal, or otherwise potentially harmful to Delphi systems. 

Please note: If you use one of our clients to access the API, you will want to update to the latest version to get API key support ([delphi-epidata](https://cmu-delphi.github.io/delphi-epidata/api/client_libraries.html) v4.1.0; [covidcast](https://cmu-delphi.github.io/delphi-epidata/api/covidcast_clients.html) R v0.5.0 / Python v0.2.0).

If you regularly or frequently use our system, please consider using an API key even if your usage falls within the anonymous usage limits. API key usage helps us understand who and how others are using our Delphi Epidata API, which may in turn inform our future research, data partnerships, and funding.

A temporary key is available for anyone whose systems have trouble with the reminder messages during rollout, to give you more time to register thoughtfully. We would much rather see a complete registration than one that was filled out quickly to meet a deadline. If you run such a system, you may use the key "TEMP-API-KEY-EXPIRES-2023-06-28", which will remain active until 2023-06-28.

For more information about how we use the data you provide us through your registration and API request activity, see our [Privacy Statement](https://cmu-delphi.github.io/delphi-epidata/api/privacy_statement.html). At any time, you may submit a [Deletion Request](https://api.delphi.cmu.edu/epidata/admin/removal_request) to have us deactivate your key and destroy all information associating that key with your identity.

The following messages may appear in your Epidata response between 2023-05-24 and 2023-06-21, either in the `message` field of JSON-formatted responses, the first row of data in CSV-formatted responses, or the first list item of the `epidata` field of JSON-formatted responses closer to 2023-06-21:

```
This request exceeded the *rate limit* on anonymous requests, which will be
enforced starting 2023-06-21. To be exempt from this limit, authenticate your
requests with an API key, now available at
https://api.delphi.cmu.edu/epidata/admin/registration_form. A temporary public
key 'TEMP-API-KEY-EXPIRES-2023-06-28' is available for use between now and
2023-06-28 to give you time to register or adapt your requests without this
message continuing to break your systems.
```

```
This request exceeded the anonymous limit on *selected multiples*, which will be
enforced starting 2023-06-21. To be exempt from this limit, authenticate your
requests with an API key, now available at
https://api.delphi.cmu.edu/epidata/admin/registration_form. A temporary public
key 'TEMP-API-KEY-EXPIRES-2023-06-28' is available for use between now and
2023-06-28 to give you time to register or adapt your requests without this
message continuing to break your systems.
```

If you see one of these messages, it means that you have until 2023-06-21 to either register for an API key to send with your requests, or refactor your code so that your API usage complies with our [anonymous access policy](https://cmu-delphi.github.io/delphi-epidata/api/api_keys.html).

**Comment by karla-desouza** [comment]
Hi @krivard! I registered for an API key, but I'm still not sure how to modify my requests using the covidcast API in R. The following link from the documentation https://api.delphi.cmu.edu/epidata/covidcast/meta?api_key=your_api_key_here renders successfully with my new API key, but I'm not sure where to go from there.

**Comment by krivard** [comment]
Hi @karla-desouza! are you using a client ([covidcast](https://cmu-delphi.github.io/covidcast/covidcastR/), [epidatr](https://github.com/cmu-delphi/epidatr), one-file [delphi-epidata.R](https://github.com/cmu-delphi/delphi-epidata/blob/dev/src/client/delphi_epidata.R)) or raw HTTP requests to access the API in R?

* [covidcast client instructions](https://cmu-delphi.github.io/covidcast/covidcastR/reference/covidcast_signal.html#api-keys-1)
* [epidatr client instructions](https://github.com/cmu-delphi/epidatr#api-keys)
* delphi-epidata.R doesn't seem to have publicly-posted instructions yet (oops) but if you do `option('epidata.auth', <your api key>)` before sourcing the file that should work
* for raw HTTP requests it depends on which package you're using but adding the `Authorization` header with `Bearer <your api key>` is easiest

**Comment by karla-desouza** [comment]
I'm using the R client and adding the line you recommended works perfectly. Thank you!!

**Comment by boxydog** [comment]
Note: for delphi_epidata Epidata.auth:

```
Epidata.auth = ('epidata', API_KEY_HERE)

# Now make Epidata calls..
```
