### ISSUE TITLE
Deactivate & mothball norostat

### ISSUE THREAD

**Issue by krivard** [cmu-delphi/delphi-epidata#1205]
The norostat indicator hasn't run successfully since November 2020, and is [interfering with our current attempt to clean up formatting in this codebase](https://github.com/cmu-delphi/delphi-epidata/pull/1189#issuecomment-1601729110).

We should:
* [x] Tag the codebase as the last available version of norostat acquisition - [DONE](https://github.com/cmu-delphi/delphi-epidata/tags)
* [x] Remove [acquisition code for norostat](https://github.com/cmu-delphi/delphi-epidata/tree/dev/src/acquisition/norostat) - DONE #1207
* [x] Leave ddl, client, and server norostat items where they are (we'll still serve the data we have, we just won't try to update it anymore) - DONE
* [x] Put a note on [the norostat API documentation page](https://github.com/cmu-delphi/delphi-epidata/blob/dev/docs/api/norostat.md) saying we're no longer updating it - DONE #1207 

(Roni approves)

**Comment by melange396** [comment]
is this related to https://cmu-delphi.atlassian.net/jira/software/projects/EPID/boards/9?selectedIssue=EPID-66 ?
