### ISSUE TITLE
COVIDcast API should not hang during the acquisition cycle

### ISSUE THREAD

**Issue by krivard** [cmu-delphi/delphi-epidata#129]
This is a more serious problem with larger data imports, but even for small updates it can interact poorly with automated jobs, causing them to spuriously fail. It's not clear why this happens, and testing it outside of production may prove tricky. 

It's particularly bothersome for us at the moment, because the COVIDcast indicator pipelines depend on API calls for validation; when an automation job halts due to this issue it often means losing work (though not losing data, to my knowledge), which then requires human attention to fix and re-run manually.

**Comment by melange396** [comment]
is this improved with https://github.com/cmu-delphi/delphi-epidata/pull/150 ?
