### ISSUE TITLE
Python client -- issues with version coupling and automatic releases

### ISSUE THREAD

**Issue by melange396** [cmu-delphi/delphi-epidata#1296]
The version of the `delphi_epidata` python client is [bound to](https://github.com/cmu-delphi/delphi-epidata/blob/b5128f09779de310ccd775a8a83edb5205372291/.bumpversion.cfg#L14-L16) the version of the repository.  This means that a new version of the client is [automatically published](https://github.com/cmu-delphi/delphi-epidata/blob/94a2551315810ffa9399580f4592379c87f40a94/.github/workflows/release-helper.yml#L47-L85) to [PyPI](https://pypi.org/project/delphi-epidata/) whenever we do a release of `delphi-epidata`, even if the client code has not actually changed.  This can confuse or annoy users, as it might encourage them to do frequent but unnecessary upgrades.  There are also concerns regarding what to do if we make changes to the client interface that might break users' existing workflows -- in such a case, [Semantic Versioning](https://semver.org/) necessitates incrementing the "major" version number, but this may be undesirable to apply to the entire repository.

We can address this in a number of ways:
- Uncouple versions between the two, which lets us number the client version however we need or want.  This would involve removing the client from the existing "`bumpversion`" configuration, and would require creating a different release process (either automatic or manual -- automatic being more work up front, while manual requires remembering to perform some number of extra steps when changing the client).
- Keep the versions coupled, but only do the PyPI release if/when the client code actually changes (again, either automatic or manual with the same caveats).  Changes to the client (other than just version number) would be found in the file https://github.com/cmu-delphi/delphi-epidata/blob/dev/src/client/delphi_epidata.py and anything under the directory https://github.com/cmu-delphi/delphi-epidata/tree/dev/src/client/packaging/pypi .  I suggest this path, at least initially.

This discussion came up in #1288.  Additional points are made and details listed in that PR, starting with comment https://github.com/cmu-delphi/delphi-epidata/pull/1288#issuecomment-1731792278 .

Similar concerns may exist for the other clients in this repo.

**Comment by melange396** [comment]
We are going to do the second bullet point above, as it integrates well with checking against the most current PyPI release as mentioned in https://github.com/cmu-delphi/delphi-epidata/issues/1281#issuecomment-2104903462

**Comment by rzats** [comment]
@melange396 one quick question before I create a PR for this!

Ideally I'd like to automatically release the Python and JS clients if the relevant files have been changed, and there are GitHub Actions that [enable this](https://github.com/marketplace/actions/changed-files). However:

> Changes to the client (other than just version number) would be found in the file https://github.com/cmu-delphi/delphi-epidata/blob/dev/src/client/delphi_epidata.py and anything under the directory https://github.com/cmu-delphi/delphi-epidata/tree/dev/src/client/packaging/pypi

Currently, a couple files in these paths have `bumpversion` enabled:

```
[bumpversion:file:src/client/delphi_epidata.py] (recently changed)

[bumpversion:file:src/client/packaging/npm/package.json] (managed by bumpversion before)

[bumpversion:file:src/client/packaging/pypi/setup.py] (managed by bumpversion before)
```

So they would be changed with every release either way.

I have two potential solutions for this:

1. Do not automate the client release, instead simply decouple the Python & JS workflows as an extra manual step (and modify the release guide to mention this)
2. Rethink how we single-source the version again. As Dmitry has mentioned, there are a couple [suggested ways](https://packaging.python.org/en/latest/guides/single-sourcing-package-version/) of doing this. The 4th suggestion (a separate `VERSION` file) might make sense, as it is supported by JavaScript as well.

Which do you think is preferable?

**Comment by melange396** [comment]
There are other possibilities too:
- (1) Make the python client release steps a conditional part of the regular release process, but only when there are changes to https://github.com/cmu-delphi/delphi-epidata/blob/dev/src/client/packaging/pypi/CHANGELOG.md .  This will have a side-effect benefit of ensuring people properly document changes to the client before it gets released.
- (2) Allow the python client to have its own version progression, not linked to the version of the acquisition and server code.  This is how it is done for the [`delphi_utils` package](https://pypi.org/project/delphi-utils/) in `covidcast-indicators`.  I dont love this (and im not exactly sure why, besides the drawback i mention below), but there is some logic to having the separation.
  - There are two `.bumpversion.cfg` files, [one for `delphi_utils`](https://github.com/cmu-delphi/covidcast-indicators/blob/main/_delphi_utils_python/.bumpversion.cfg) and [one for the rest](https://github.com/cmu-delphi/covidcast-indicators/blob/main/.bumpversion.cfg).
  - The `delphi_utils` version bumping and PyPI release are conditional on changes to those files ([here](https://github.com/cmu-delphi/covidcast-indicators/blob/0c65bb468d9aa3a6c2f37d6f28a5490029b32354/.github/workflows/create-release.yml#L32-L40) and [here](https://github.com/cmu-delphi/covidcast-indicators/blob/0c65bb468d9aa3a6c2f37d6f28a5490029b32354/.github/workflows/publish-release.yml#L31-L41)).
  - AFAICT this solution has a drawback in that its not currently possible to do anything but a "`patch`" release for `delphi_utils` and not the rest, or vice-versa.
- (3) Semi-detatch the versioning, syncing the client version to the base version and doing the PyPI release only on client code changes.  This can be accomplished like so:
  - Take the two python client file mentions out of [`.bumpversion.cfg`](https://github.com/cmu-delphi/delphi-epidata/blob/dev/.bumpversion.cfg)
  - Put them into their own at [`src/client/packaging/pypi/`](https://github.com/cmu-delphi/delphi-epidata/tree/dev/src/client/packaging/pypi)`.bumpversion.cfg` (with lines for `[bumpversion:file:setup.py]` and `[bumpversion:file:../../delphi_epidata.py]`, hopefully itll accept the "up" directory pathing).
  - Conditionally initiate a `bump2version` command in https://github.com/cmu-delphi/delphi-epidata/blob/dev/.github/workflows/create-release.yml using that `.../pypi/` as the working directory, when changes are detected in any of the client files...
    - but dont run it with `${{ github.event.inputs.versionName }}` as the version argument;
    - use `${{ steps.version.outputs.next_tag }}` instead.
  - Finally, in https://github.com/cmu-delphi/delphi-epidata/blob/dev/.github/workflows/release-helper.yml , make the PyPI step again conditional on changes to the client files.

I like the last one best but i could be convinced to go along with the `CHANGELOG`-dependent one.

**Comment by rzats** [comment]
@melange396 I've implemented your last idea in https://github.com/cmu-delphi/delphi-epidata/pull/1465!
