### ISSUE TITLE
Consider basing COVIDcast metadata min/max/stdev based on specific date range

### ISSUE THREAD

**Issue by capnrefsmmat** [cmu-delphi/delphi-epidata#130]
One issue raised repeatedly about the COVIDcast map is that the color scale is based on the minimum, maximum, and standard deviation of the entire signal history. If a signal has changed significantly over time, the map can hence be poorly scaled.

Figuring out how to adjust the scale dynamically when the user switches days is one problem; but before it can do that, the `covidcast_meta` endpoint would have to provide metadata about a specific date or date range. For example, if we said the scale is based on the variation over the past month, we'd need to be able to request the scale for 2020-04-20 and get the variation over the preceding month.

Unfortunately this would break the caching strategy we currently use, so it also remains to be seen whether there is an efficient way to do this. I wonder whether the strategy might end up being "just stick [Varnish](https://varnish-cache.org/) in front of the API server" instead of a clever caching system, but I don't know what will prove best.

**Comment by krivard** [comment]
Roni proposes a leaky-capacitor model for a per-day set of min/max/mean/stdev computations that weight recent data more heavily than distant data. This could be constructed incrementally to reduce the computation cost at acquisition time, but we'd want to consider whether to implement it as a separate signal (and all the database and server overhead that includes) or by overloading `covidcast` with a dedicated geo level for the purpose.

**Comment by krivard** [comment]
wontfix
