### ISSUE TITLE
KCDC data is old (Oct 2020)

### ISSUE THREAD

**Issue by nmdefries** [cmu-delphi/delphi-epidata#1344]
```
library(epidatr)
librar(dplyr)
pub_kcdc_ili(regions = "ROK", epiweeks = epirange(200001, 202350)) %>% pull(epiweek) %>% max()
# [1] "2020-10-25"
```

Is the source no longer reporting flu data? Is our pipeline broken? Has the data page changed location? The [URL](https://github.com/cmu-delphi/delphi-epidata/blob/7a27a3a/src/acquisition/kcdc/kcdc_update.py#L97) we had been using now redirects to kdca.go.kr.

**Comment by korlaxxalrok** [comment]
🤯

**Comment by nmdefries** [comment]
Not resurrecting. Site is down.
