### ISSUE TITLE
`covid_hosp_state_timeseries` doesn't return any data

### ISSUE THREAD

**Issue by nmdefries** [cmu-delphi/delphi-epidata#1367]
I can't get `pub_covid_hosp_state_timeseries` (via `epidatr`) to return data. I've tried different states, different state name formats, different narrow and broad date ranges.

**Comment by melange396** [comment]
do you know what request URIs are being generated?  here is a functioning one (once you delete the "`.remove`" substring in the hostname) : https://api.delphi.cmu.edu.remove/epidata/covid_hosp_state_timeseries/?states=pa&dates=20231101

**Comment by nmdefries** [comment]
Seems like I wasn't requesting recent enough date ranges. This is working for me now!
