### ISSUE TITLE
covidcast_meta API Down?

### ISSUE THREAD

**Issue by wlf211** [cmu-delphi/delphi-epidata#138]
Hey, noticed this morning that https://delphi.cmu.edu/epidata/api.php?source=covidcast_meta is not responding, has anything changed with the way to access this endpoint?

Have been using the sample string provided at: https://cmu-delphi.github.io/delphi-epidata/api/covidcast_meta.html

Thanks!

**Comment by krivard** [comment]
Ah, we should change that sample to ask for the cached version. We now have enough data that the live computation times out. We have a fix in the works that will circumvent this in the future, just going through final checks before deploying it. Thanks for the report!

@capnrefsmmat -- can we slip an update into the API docs update for 1.4? just adding `cached=true` to the sample meta URL on the COVIDcast front-page.

**Comment by capnrefsmmat** [comment]
Will do -- I'll change the link to be https://delphi.cmu.edu/epidata/api.php?source=covidcast_meta&cached=true

Let me also take this opportunity to suggest subscribing to our new [API mailing list](https://lists.andrew.cmu.edu/mailman/listinfo/delphi-covidcast-api), where we will try to announce any important changes or availability issues.
