### ISSUE TITLE
Clarify whether the “Other Endpoints” section is meant to include COVID + other diseases, or just other diseases

### ISSUE THREAD

**Issue by tinatownes** [cmu-delphi/delphi-epidata#1398]
In the docs pages, are “Other Endpoints” meant to be COVID + other diseases or just other diseases? The description page seems to contradict what is noted in left side menu:

![image](https://github.com/cmu-delphi/delphi-epidata/assets/11445176/c6d27195-7f1b-4f77-aa39-2271de17bdf8)

**Comment by melange396** [comment]
The "covidcast" endpoint provides some information relating to flu (and some other things that arent covid as well), and the other endpoints do provide some covid information too...  "covidcast" will get renamed/rebranded in the not-too-distant future, but for now, the title of "Epidata API (Other Diseases)" would best be changed to match the text in the sidebar.  The sentence you underlined can probably be removed unless you have an idea for changing it to be something more accurate.
