### ISSUE TITLE
Add descriptive links to other endpoint pages

### ISSUE THREAD

**Issue by nmdefries** [cmu-delphi/delphi-epidata#1515]
Add

- [x] [this link](https://9to5google.com/2020/03/23/google-coronavirus-survey/) to the [google survey page](https://github.com/cmu-delphi/delphi-epidata/blob/d7903456e67c8f307a4e5d12bb132d0aa6801fd5/docs/api/covidcast-signals/google-survey.md)
- [x] these two (Social Distancing Metrics (https://docs.safegraph.com/docs/social-distancing-metrics); Weekly Patterns (https://docs.safegraph.com/docs/weekly-patterns)) to the Safegraph page
- [x] [this link](https://console.cloud.google.com/marketplace/product/bigquery-public-datasets/covid19-search-trends?q=search&referrer=search&project=southern-guild-298314) to the google symptoms page
- [x] links to or lists of [county](https://github.com/cmu-delphi/delphi-epidata/blob/7a27a3a/src/acquisition/nidss/taiwan_nidss.py#L51) and [region](https://github.com/cmu-delphi/delphi-epidata/blob/7a27a3a/src/acquisition/nidss/taiwan_nidss.py#L79) (Taipei, Northern, Central, etc) options + "Nationwide" on the nidss pages. [Dengue](https://cmu-delphi.github.io/delphi-epidata/api/nidss_dengue.html) has counties and regions and nationwide; [flu](https://cmu-delphi.github.io/delphi-epidata/api/nidss_flu.html) doesn't have counties
- [x] Turn [these links](https://cmu-delphi.github.io/delphi-epidata/api/flusurv.html#flusurv-data) into actual clickable hyperlinks
- [x] add [this link](https://www.google.com/publicdata/explore?ds=z3bsqef7ki44ac_) and [this link](https://en.wikipedia.org/wiki/Google_Flu_Trends) to the [GFT doc page](https://cmu-delphi.github.io/delphi-epidata/api/gft.html).
- [x] add [this link](https://trends.google.com/trends/fullscreen/m/IN) to the [GHT page](https://cmu-delphi.github.io/delphi-epidata/api/ght.html). there are various research papers talking about using GHT for health tracking. maybe we can add links to some of those to provide more background about the source

**Comment by nmdefries** [comment]
- [ ] add [license info](https://data.gov.tw/license) for Taiwanese datasets

**Comment by nmdefries** [comment]
- [ ] in “[COVID-19 Reported Patient Impact and Hospital Capacity by State Timeseries](https://cmu-delphi.github.io/delphi-epidata/api/covid_hosp.html)”, the URL example is woefully out of date, e.g. it doesn’t show the fields with age breakdown.  Re-executing the same URL returns an updated list, that should be put into the example in the documentation.

**Comment by tinatownes** [comment]
Addressed with pull request #1552
