### ISSUE TITLE
Add source citation to `twitter` endpoint

### ISSUE THREAD

**Issue by nmdefries** [cmu-delphi/delphi-epidata#1524]
[Twitter endpoint](https://cmu-delphi.github.io/delphi-epidata/api/twitter.html).

Mark Dredze, Renyuan Cheng, Michael J Paul, David A Broniatowski. HealthTweets.org: A Platform for Public Health Surveillance using Twitter. AAAI Workshop on the World Wide Web and Public Health Intelligence, 2014.

**Comment by tinatownes** [comment]
See pull request #1543
