### ISSUE TITLE
question regarding publish docs to gh-pages

### ISSUE THREAD

**Issue by sgratzl** [cmu-delphi/delphi-epidata#175]
as far as I can see you have a github action that copies the /docs directory to the gh-pages branch. 

However, github directly let you select the main branch and the `/docs` directory underneath it as the gh-pages source, so there would be no need for that:

![image](https://user-images.githubusercontent.com/4129778/89530819-6df2b680-d7ef-11ea-985e-8256d0096be2.png)

**Comment by capnrefsmmat** [comment]
Ah, this is a brand-new feature: previously you could only do this is the branch was named `master`, not if the branch was named, say, `main`. But now they let us choose the branch to deploy from, so we could switch to this.

**Comment by sgratzl** [comment]
fixed with #590
