### ISSUE TITLE
how to pull unrevised ILI rates at the HHI or state level?

### ISSUE THREAD

**Issue by randomgambit** [cmu-delphi/delphi-epidata#18]
Hello there!

Thanks for this amazing package. I would like to know if I can use `delphi-epidate` to retrieve the original, unrevised ILI rates **estimates** available during a given week (at the HHI or State level).

That is, the equivalent of https://www.cdc.gov/flu/weekly/weeklyarchives2013-2014/data/senAllregt08.htm but at the HHI or state level (instead of at the national level).

Is this information available through this package?
Thanks!

**Comment by brookslogan** [comment]
Yes, (some) unrevised ILINet data is available via delphi-epidata: please try the "issue" and "lag" arguments [for the "fluview" source](https://github.com/cmu-delphi/delphi-epidata#fluview-parameters).

Examples of what these terms mean:
- issue 201905: refers to the CDC report containing the first version of data for week 201905 (which was published on Friday of week 201906).
- epiweek 201905, issue 201905: first version of the data for week 201905
- epiweek 201905, lag 0: the same thing (first version of the data for week 201905)
- epiweek 201905, issue 201906: second version of the data for week 201906 (its first revision)
- epiweek 201905, lag 1: the same thing (second version / first revision of the data for week 201905)

Some issues or parts of issues may be unavailable for earlier years, and availability depends on the geographical level.  For national and regional data for the past 5 years, you shouldn't encounter any problems; beyond that, there may be some holes to deal with.  State-level revision data are only available for the past 2 years.

You can also load and visualize these data in your browser using the [EpiVis interface](https://delphi.midas.cs.cmu.edu/epivis/epivis.html).

**Comment by randomgambit** [comment]
thanks! this is really great!!!

**Comment by randomgambit** [comment]
@brookslogan so if I understand well for obtain all the revisions of a given `epiweek` over time, I need to loop over the `issue` argument. 

More precisely, for week W, I need to iterate from `issue = epiweek W+7` to `issues = last week of the season`. Is that right? What is the last week of the season?

Last, can we assume that during week `W`, all the revisions up to week `W-7` (the previous week) are known to forecasters?

Thanks!

**Comment by brookslogan** [comment]
The first version would be issue = W.  CDC's Epidemic Prediction Initiative considers issue week 28 data stable enough for forecast evaluation for the preceding season (i.e., issue 201828 for the 2017/2018 season, which spans epiweeks 201740--201820).  However, the data can still experience revisions after issue week 28; we usually record a year's worth of revisions (i.e., issues up to W+51), but sometimes record revisions that occurred even later.

Other notes:
- The Epidata API accepts a range of epiweeks and/or issues and/or lags as parameters, although there is a limit on the number of rows returned; using these ranges may be faster than manually looping.
- Individual epiweek and issue numbers are expected to be in the format YYYYWW; to get to the next week, you would usually add one (although there's wrapping to consider at the end of the calendar year).

**Comment by randomgambit** [comment]
@brookslogan thanks that is very useful!
