### ISSUE TITLE
how to check if the data is correct?

### ISSUE THREAD

**Issue by randomgambit** [cmu-delphi/delphi-epidata#19]
Hello, I was looking at the official https://gis.cdc.gov/grasp/fluview/fluportaldashboard.html and my understanding is that only the final ILI values are reported.

Despite one's best efforts, sometimes there are mistakes or parsing errors. How can I check that the historical (**those that are revised over time**) ILI values are correct when using `delphi-epidata`?

I am thinking about running some manual checks for a few random dates. 

Thanks again for this great API!

**Comment by randomgambit** [comment]
of course, I will let you know if I find some discrepancies so that the package can be further improved! Thanks!

**Comment by randomgambit** [comment]
@brookslogan any ideas? :) thanks for helping out!

**Comment by brookslogan** [comment]
A couple of potential options: you could try comparing against [this previous dump of data from the API](https://github.com/reichlab/2018-2019-cdc-flu-contest/blob/master/data/flu_data_with_backfill.rds), or by downloading the data from FluView Interactive (your link above) and waiting a week.

**Comment by randomgambit** [comment]
Thank you so much, @brookslogan. I will give it a try a let you know.

**Comment by krivard** [comment]
This work is being folded into a separate data validation crawling effort.
