### ISSUE TITLE
Putting clients in package indices

### ISSUE THREAD

**Issue by lepisma** [cmu-delphi/delphi-epidata#2]
Hello,

I was wondering if its possible to put the client code as packages on corresponding language repositories (pypi. npm and cran). That would make using/setting them easier than the current method where users need to pull in updates to code manully.

**Comment by undefx** [comment]
That's a great idea. I don't have the time to work on this immediately, but I'll definitely leave this issue up until I can get to it.

**Comment by lepisma** [comment]
Looks like the github regex misfired.

**Comment by undefx** [comment]
Thanks for letting me know! Reopening.

I'll have to be more careful with my commit messages haha...

**Comment by krivard** [comment]
delphi-epidata is up on [PyPI](https://pypi.org/project/delphi-epidata/) and [NPM](https://www.npmjs.com/package/delphi_epidata) but not on CRAN (and we have no plans to put it there)
