### ISSUE TITLE
Catch missing '$' and other bad PHP

### ISSUE THREAD

**Issue by krivard** [cmu-delphi/delphi-epidata#212]
In theory the integration tests should have caught [this typo](https://github.com/cmu-delphi/delphi-epidata/pull/211); in practice everything passed and then promptly crashed in production. We need to 

- [ ] Figure out what happened
- [ ] If it's something we can test for using the current rig, do so
- [ ] If not, figure out what is needed for adequate testing, and build out the infrastructure to support it

**Comment by dfarrow0** [comment]
Looks like function [`send_csv`](https://github.com/cmu-delphi/delphi-epidata/search?q=send_csv) is not called in any integration tests.

Recommend adding integration tests for `send_csv`, and also `send_json`, which appears to be related.

**Comment by sgratzl** [comment]
what about: 

https://github.com/cmu-delphi/delphi-epidata/blob/801f2729ea80b42891aa282c858c489a47049082/integrations/server/test_covidcast.py#L83-L150

**Comment by dfarrow0** [comment]
oh you're right, i totally missed that, thanks for pointing it out.

**Comment by dfarrow0** [comment]
when the `$` is missing, the integration test passes, but the server logs the following:

```
[Thu Oct 08 10:12:51.386119 2020] [php7:warn] [pid 18] [client 172.18.0.1:39892] PHP Warning:  Use of undefined constant data - assumed 'data' (this will throw an Error in a future version of PHP) in /var/www/html/epidata/api_helpers.php on line 393
[Thu Oct 08 10:12:51.386140 2020] [php7:warn] [pid 18] [client 172.18.0.1:39892] PHP Warning:  Illegal string offset 'result' in /var/www/html/epidata/api_helpers.php on line 393
```

it would be nice to somehow tell php to treat this particular warning (or maybe all warnings) as an error. unfortunately i don't see a good way of doing that. the recommended approach seems to be to overriding the global error handler, which is less than ideal imo.

**Comment by sgratzl** [comment]
isn't there some linting tool that catches those kind of errors during a static analysis?

**Comment by sgratzl** [comment]
can we close this since we switched to Flask + Python?

**Comment by krivard** [comment]
Yep!
