### ISSUE TITLE
Chrome cookie issue

### ISSUE THREAD

**Issue by sgratzl** [cmu-delphi/delphi-epidata#214]
in the latest chrome I get the following issue warning:

![image](https://user-images.githubusercontent.com/4129778/92735486-bd417f00-f379-11ea-9947-4d333153c55a.png)

**Comment by krivard** [comment]
@korlaxxalrok I don't think the API proper is using cookies, but the cookie
name prefix "AWS" makes me think this has something to do with the clones.
Any ideas?

**Comment by capnrefsmmat** [comment]
It appears to exist so people get directed to the same endpoint in the pool on every request. Probably not necessary, since the API is stateless: https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-target-groups.html#sticky-sessions

**Comment by korlaxxalrok** [comment]
We have access to the AWS env now so I can take a look at this.

**Comment by sgratzl** [comment]
I don't see any errors anymore when calling https://api.covidcast.cmu.edu/epidata/api.php?source=covidcast_meta&cached=true -> closing
