### ISSUE TITLE
Accept a list of geo_values instead of only a single value

### ISSUE THREAD

**Issue by capnrefsmmat** [cmu-delphi/delphi-epidata#221]
Currently, the covidcast endpoint accepts a single `geo_value` that can either be `*` (all locations) or the identifier of a single location. That means that if an API client wants to fetch, say, the top 500 counties by case counts, they either have to send one query and filter it or send 500 separate queries. The R and Python clients currently do the latter, but it's slow. (Fetching one day of data for 500 counties would take as long as fetching all state data for 500 days -- making it unusably slow if you want more than one or two days of data.)

Can `geo_value` take a comma-separated list, like the issues and time_values parameters?

For new people, the code lives here: https://github.com/cmu-delphi/delphi-epidata/blob/main/src/server/api.php#L940

**Comment by sgratzl** [comment]
similarly it would be nice if one cannot only set multiple geo_values but that they also might have different geo_types. e.g. then you can query a county and its state at the same time
