### ISSUE TITLE
Fix problem with host permissions in Docker definition

### ISSUE THREAD

**Issue by krivard** [cmu-delphi/delphi-epidata#225]
While debugging this error:

```
$ sudo docker run --rm -p 13306:3306   --network delphi-net --name delphi_database_epidata   delphi_database_epidata
[...]
2020-09-24 14:25:44-04:00 [Note] [Entrypoint]: /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/api_analytics.sql
/usr/local/bin/docker-entrypoint.sh: line 72: /docker-entrypoint-initdb.d/api_analytics.sql: Permission denied
```

@brookslogan and Mike discovered that something seems to be amiss in the Docker definition for epidata that causes world to be denied all access to .sql files, like so:

```
$ sudo docker start delphi_database_epidata
delphi_database_epidata
$ sudo docker exec -it delphi_database_epidata /bin/bash
root@157020b36924:/# whoami
root
root@157020b36924:/#  ls -al docker-entrypoint-initdb.d
total 88
drwxr-xr-x 1 root root  4096 Sep 24 14:25 .
drwxr-xr-x 1 root root  4096 Sep 25 14:30 ..
-rwxr-x--- 1 root root  1262 Sep 21 15:25 api_analytics.sql
-rwxr-x--- 1 root root  3410 Sep 21 15:25 cdc.sql
-rwxr-x--- 1 root root  6435 Sep 21 15:25 covidcast.sql
-rwxr-x--- 1 root root  1193 Sep 21 15:25 ecdc_ili.sql
-rwxr-x--- 1 root root 15422 Sep 21 15:25 fluview.sql
-rwxr-x--- 1 root root   878 Sep 21 15:25 forecasts.sql
-rwxr-x--- 1 root root   887 Sep 21 15:25 gft.sql
-rwxr-x--- 1 root root  1016 Sep 21 15:25 ght.sql
-rwxr-x--- 1 root root  1160 Sep 21 15:25 kcdc_ili.sql
-rwxr-x--- 1 root root  2404 Sep 21 15:25 nidss.sql
-rwxr-x--- 1 root root   984 Sep 21 15:25 nowcasts.sql
-rwxr-x--- 1 root root  1727 Sep 21 15:25 paho_dengue.sql
-rwxr-x--- 1 root root  1093 Sep 21 15:25 quidel.sql
-rwxr-x--- 1 root root  1017 Sep 21 15:25 sensors.sql
-rwxr-x--- 1 root root   889 Sep 21 15:25 twitter.sql
-rwxr-x--- 1 root root  3984 Sep 21 15:25 wiki.sql
root@157020b36924:/# 
```

The correct permissions for world should be read-only.

Running `chmod o+r` on all the .sql files works, so fixing this permanently will require something like adding the following to the Dockerfile:

```
RUN chmod o+r /docker-entrypoint-initdb.d/*.sql
```

**Comment by sgsmob** [comment]
A similar issue is also present when starting `delphi_web_epidata` and I am working now to verify it can be fixed with a similar solution.

**Comment by sgsmob** [comment]
> A similar issue is also present when starting `delphi_web_epidata` and I am working now to verify it can be fixed with a similar solution.

It does

**Comment by dfarrow0** [comment]
i'm so confused on what changed to cause this to break. i'm happy to dig in once i fix my docker install.

note that there are several not-so-obvious places where files are copied into images, so there may be more instances of this to track down.

**Comment by krivard** [comment]
yeah, it is a bit spooky -- it might come down to differences in individual Docker installations. Since they're just used for dev though I'm happy to support the most lenient requirements needed for everybody's setup to work.
