### ISSUE TITLE
integrations tests failing at head

### ISSUE THREAD

**Issue by dfarrow0** [cmu-delphi/delphi-epidata#251]
Integration tests are failing, e.g. https://github.com/cmu-delphi/delphi-epidata/runs/1260920716

```
 delphi.delphi-epidata.integrations.client.test_delphi_epidata.DelphiEpidataPythonClientTests.test_covidcast: fail
```

**Comment by krivard** [comment]
Multi-signal queries in the URL are turning into single-signal queries by the time the SQL is constructed, but the same thing is not happening to multi-geo queries. Investigating.

We may need to add a test merge phase to CI and/or the review procedure, since this didn't come up in whatever PR introduced it.

**Comment by krivard** [comment]
...and now my docker setup is confused (`mysql.connector.errors.InterfaceError: 2003: Can't connect to MySQL server on 'delphi_database_epidata:3306' (111 Connection refused)`) ☹️ 

Some spot checks verify that this problem is not manifesting in production even though [deployment status claims it should be up to date with HEAD](68747470733a2f2f64656c7068692e636d752e6564752f7e6175746f6d6174696f6e2f7075626c69632f6769746875625f6465706c6f795f7265706f2f62616467652e7068703f7265706f3d636d752d64656c7068692f64656c7068692d65706964617461). If something pops up over the weekend let me know, otherwise I'll return to this on Monday.

**Comment by dfarrow0** [comment]
Looking a little closer, this is actually more of a problem than I initially realized.

The test is pretty straightforward: it adds 3 rows for `sig` and 1 row for `sig2`. Then it requests the most recent values for both. The API should return one row for each signal. But instead, the API returns just a single row, which is **incorrect**.

I strongly suspect this has to do with the new column `is_latest_issue`, but I haven't confirmed yet.

---

Some more details. Here's what's in the database:

```
+----+--------+--------+-----------+----------+------------+-----------+-------------------------+-------+--------+-------------+-----------------------------+-----------+----------+-----+-----------------+--------+
| id | source | signal | time_type | geo_type | time_value | geo_value | value_updated_timestamp | value | stderr | sample_size | direction_updated_timestamp | direction | issue    | lag | is_latest_issue | is_wip |
+----+--------+--------+-----------+----------+------------+-----------+-------------------------+-------+--------+-------------+-----------------------------+-----------+----------+-----+-----------------+--------+
|  1 | src    | sig    | day       | county   |   20200414 | 01234     |                     123 |   1.5 |    2.5 |         3.5 |                         456 |         4 | 20200414 |   0 | 0               | 0      |
|  2 | src    | sig2   | day       | county   |   20200414 | 01234     |                     123 |   1.5 |    2.5 |         3.5 |                         456 |         4 | 20200414 |   0 | 0               | 0      |
|  3 | src    | sig    | day       | county   |   20200414 | 01234     |                     456 |   5.5 |    1.2 |        10.5 |                         789 |         0 | 20200415 |   1 | 0               | 0      |
|  4 | src    | sig    | day       | county   |   20200414 | 01234     |                     345 |   6.5 |    2.2 |        11.5 |                         678 |         0 | 20200416 |   2 | 1               | 0      |
+----+--------+--------+-----------+----------+------------+-----------+-------------------------+-------+--------+-------------+-----------------------------+-----------+----------+-----+-----------------+--------+
```

**Notice that `is_latest_issue` is only true for "sig", not for "sig2".**

Here's what the client requests:

```
/epidata/api.php?source=covidcast&data_source=src&signals=sig%2Csig2&time_type=day&geo_type=county&time_values=20200414&geo_value=01234
```

Here's the server's query, and result:

```
MariaDB [epidata]> SELECT t.`signal`, t.`time_value`, t.`geo_value`, t.`value`, t.`stderr`, t.`sample_size`, t.`direction`, t.`issue`, t.`lag` FROM `covidcast` t  WHERE (t.`source` = 'src') AND ((t.`signal` = 'sig') OR (t.`signal` = 'sig2')) AND (t.`time_type` = 'day') AND (t.`geo_type` = 'county') AND ((t.`time_value` = 20200414)) AND (t.`geo_value` = '01234') AND ((t.`is_latest_issue` IS TRUE)) ORDER BY t.`signal` ASC, t.`time_value` ASC, t.`geo_value` ASC, t.`issue` ASC;
+--------+------------+-----------+-------+--------+-------------+-----------+----------+-----+
| signal | time_value | geo_value | value | stderr | sample_size | direction | issue    | lag |
+--------+------------+-----------+-------+--------+-------------+-----------+----------+-----+
| sig    |   20200414 | 01234     |   6.5 |    2.2 |        11.5 |         0 | 20200416 |   2 |
+--------+------------+-----------+-------+--------+-------------+-----------+----------+-----+
```

The client receives:

```
{
    "result": 1,
    "epidata": [
        {
            "geo_value": "01234",
            "signal": "sig",
            "time_value": 20200414,
            "direction": 0,
            "issue": 20200416,
            "lag": 2,
            "value": 6.5,
            "stderr": 2.2,
            "sample_size": 11.5
        }
    ],
    "message": "success"
}
```

---

Finally, more of a meta-comment. This failure doesn't really have anything to do with the python client. This test might have a better home in `integrations/server/test_covidcast.py` rather than `integrations/client/test_delphi_epidata.py`. But not a big deal, it's kindof subjective. But in any case, it's somewhat concerning that `test_covidcast.py` didn't catch this.

**Comment by dfarrow0** [comment]
Ok so maybe false alarm. The test inserts this data:

```
      insert into covidcast values
        (0, 'src', 'sig', 'day', 'county', 20200414, '01234',
          123, 1.5, 2.5, 3.5, 456, 4, 20200414, 0, 0, False),
        (0, 'src', 'sig2', 'day', 'county', 20200414, '01234',
          123, 1.5, 2.5, 3.5, 456, 4, 20200414, 0, 0, False),
        (0, 'src', 'sig', 'day', 'county', 20200414, '01234',
          456, 5.5, 1.2, 10.5, 789, 0, 20200415, 1, 0, False),
        (0, 'src', 'sig', 'day', 'county', 20200414, '01234',
          345, 6.5, 2.2, 11.5, 678, 0, 20200416, 2, 1, False)
```

The insert doesn't have any row with `is_latest_issue` for "sig2". So maybe you could say it's not the API's fault that the test inserted bad data. It's not clear from the test whether this is intentional, but I'm guessing not since the test is failing.

In that case, recommend just setting `is_latest_issue` for the "sig2" row.
