### ISSUE TITLE
Broken link in delphi-epidata documentation

### ISSUE THREAD

**Issue by huisaddison** [cmu-delphi/delphi-epidata#310]
The page https://cmu-delphi.github.io/delphi-epidata/ has a link:

> The Delphi group is extremely grateful for Pedrito Maynard-Zhang for all his help with the Epidata API [documentation].

^ [documentation] points to:  https://cmu-delphi.github.io/delphi-epidata/api/index.md which generates a 404 error.  Was the file deleted or misplaced during a site migration?

**Comment by capnrefsmmat** [comment]
I think it should point to `api/README.md` instead of `api/index.md`.

**Comment by krivard** [comment]
Fixed in #311
