### ISSUE TITLE
Update Coffee, JS, and R client to fall back to POST requests

### ISSUE THREAD

**Issue by chinandrew** [cmu-delphi/delphi-epidata#316]
See discussion + changes in #309 for Python client.

**Comment by chinandrew** [comment]
@krivard opened identical issue with a better description so closing this one. However, I'd like to point out that this issue was opened 3 seconds earlier.

![Screenshot from 2020-12-08 13-32-24](https://user-images.githubusercontent.com/20176218/101544154-1198d280-395a-11eb-99ed-27fae82c7449.png)
![Screenshot from 2020-12-08 13-32-35](https://user-images.githubusercontent.com/20176218/101544159-12316900-395a-11eb-96b5-b49e2358523e.png)

**Comment by dfarrow0** [comment]
:laughing:

**Comment by capnrefsmmat** [comment]
Even better -- it's 2020-12-08T21:31:48Z vs 2020-12-08T21:31:50Z, according to the page source, so you were 2 seconds faster at the draw. Time to change your avatar to Clint Eastwood.
