### ISSUE TITLE
Change name of first parameter from 'source' to 'endpoint' 

### ISSUE THREAD

**Issue by RoniRos** [cmu-delphi/delphi-epidata#321]
This has been confusing to outsiders (e.g. email from Nick Reich, but probably just about everyone) with the 'signal source' parameter.

The same 'thing' should be called by the same name...

@undefx told me he agrees and suggested maybe @krivard or @capnrefsmmat could do or else oversee it?

No real rush, but maybe a good intro task for someone?

**Comment by krivard** [comment]
Agreed, this is more in keeping with our current documentation wrt COVIDcast vs the other endpoints.

Sam -- this is not urgent, so anything for a viz deadline should take priority, but if you have free cycles take a look? We'll probably want the solution to be backwards-compatible so as not to break people's pipelines if they have old copies of the Epidata and/or covidcast clients.

**Comment by sgratzl** [comment]
just to clarify, it is about that the first API.php parameter is called `source`. But should be renamed to `endpoint` in a backwards compatible way?

related code:
https://github.com/cmu-delphi/delphi-epidata/blob/7220a12cd7709d9db13b95edac7993f5835a444c/src/server/api.php#L1322

**Comment by dfarrow0** [comment]
Yeah that's correct.

**Comment by sgratzl** [comment]
related PRs
 * here: https://github.com/cmu-delphi/delphi-epidata/pull/325
 * covidcast: https://github.com/cmu-delphi/covidcast/pull/379
 * www-covidcast: https://github.com/cmu-delphi/www-covidcast/pull/682#issuecomment-743348502

**Comment by krivard** [comment]
Fixed in #349
