### ISSUE TITLE
Survey question coding error in Wave 5 B2c item numbers

### ISSUE THREAD

**Issue by krivard** [cmu-delphi/delphi-epidata#322]
The survey question pdf for Wave 5 shows B2c's "Other (please specify)" as item 18, but it is coded in the qualtrics files as item 14 (presumably to match Wave 4):

```
$ grep -o "B2c_[0-9]*_TEXT" input/2020-12-11.2020-12-04.2020-12-11.Survey_of_COVID-Like_Illness_-_*
input/2020-12-11.2020-12-04.2020-12-11.Survey_of_COVID-Like_Illness_-_Wave_4.csv:B2c_14_TEXT
input/2020-12-11.2020-12-04.2020-12-11.Survey_of_COVID-Like_Illness_-_Wave_5.csv:B2c_14_TEXT
```

The file to be corrected is here:
* https://cmu-delphi.github.io/delphi-epidata/symptom-survey/waves/Survey_of_COVID-Like_Illness_-_Wave_5.pdf

(& probably the word doc file as well)

**Comment by capnrefsmmat** [comment]
It looks like this is a bug in the Qualtrics exporter. Qualtrics shows the coded values correctly in its interface, and the Word file comes directly from Qualtrics's export function, but then gets the coding for B2c wrong. I suspect there's some interaction where B2c carries over choices from B2, and the coding is applied correctly to B2 but not B2c.

@WichadaLMK I think you'll have to just manually adjust the coding shown in the Word doc, then save that and export a PDF as well. Then I can update the docs site.

**Comment by WichadaLMK** [comment]
Hmmm… I think there were some last minute changes made that the PDF doesn’t reflect. I didn’t have to manually change anything and this is the copy I have and should be correct.

**Comment by krivard** [comment]
@capnrefsmmat did this get fixed?

**Comment by capnrefsmmat** [comment]
Yes, the PDF is updated. I also checked the codebook CSV and it appears correct, so we must have fixed this in late 2020 or early 2021.
