### ISSUE TITLE
Document new geography types for covidcast

### ISSUE THREAD

**Issue by capnrefsmmat** [cmu-delphi/delphi-epidata#323]
The geographic coding page does not yet list HHS and nation, or say which values are accepted for them: https://cmu-delphi.github.io/delphi-epidata/api/covidcast_geography.html

It should list both and say what geographic IDs are used. (Do you request nation with `geo_value="us"`? "usa"? Something else)

**Comment by krivard** [comment]
Good call.

@Akvannortwick here are the details:

The `nation` values that are accepted are the ISO 3166-1 alpha-2 country codes (https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2). Currently the only nation we have data on is `us`.

The `hhs` values that are accepted are the numbers 1-10, corresponding to the US Department of Health & Human Services Regional Offices (https://www.hhs.gov/about/agencies/iea/regional-offices/index.html)

**Comment by krivard** [comment]
Fixed by #326
