### ISSUE TITLE
Consider improving EpiData JS client

### ISSUE THREAD

**Issue by sgratzl** [cmu-delphi/delphi-epidata#327]
possible improvements:
 * switch to `fetch` api for clients in case JQuery is not available
 * create a Promise based version (e.g. `covidcastAsync(...)`) which works great with await/async
 * remove coffee version and create a clean JS version - is anyone using CoffeeScript these days?
 * create TypeScript typings for better auto completion
 * publish on NPM for easier (versioned) CDN usage

**Comment by dfarrow0** [comment]
sounds great to me :)

**Comment by krivard** [comment]
I'm a fan too. @sgratzl are you volunteering? It would be lower priority than whatever Chris needs you to do, but if you have hours to fill...

**Comment by sgratzl** [comment]
sure

**Comment by sgratzl** [comment]
done, except the NPM release

**Comment by sgratzl** [comment]
closing will be part of #600
