### ISSUE TITLE
consider using pytest for unit tests

### ISSUE THREAD

**Issue by sgratzl** [cmu-delphi/delphi-epidata#338]
[py.test](https://docs.pytest.org/en/latest/) is a standard python unit testing framework/testing environment which has also plugins for various outputs. One might consider switching to that over the custom py3tester one

**Comment by krivard** [comment]
py3tester is the Delphi Classic(tm) framework; indicators currently uses pytest and so does covidcast. I'm in favor of switching us over to industry-maintained toolchains as much as possible.

**Comment by sgratzl** [comment]
the new CI + flask version are using pytest already -> closing
