### ISSUE TITLE
Ensure "First issued" is listed in the header of the API documentation for all COVIDcast sources

### ISSUE THREAD

**Issue by krivard** [cmu-delphi/delphi-epidata#357]
The first column here are the first issues for every source:

```
+-----------------------+------------+-----------------+
| source                | min(issue) | min(time_value) |
+-----------------------+------------+-----------------+
| cds-test              |   20200728 |        20200220 |
| chng                  |   20201104 |        20200201 |
| doctor-visits         |   20200429 |        20200201 |
| facere                |   20200529 |        20200201 |
| fb-survey             |   20200429 |        20200406 |
| ght                   |   20200429 |        20200201 |
| google-survey         |   20200429 |        20200411 |
| google-symptoms       |   20201130 |        20200213 |
| hospital-admissions   |   20200621 |        20200201 |
| indicator-combination |   20200520 |        20200220 |
| jhu-csse              |   20200507 |        20200122 |
| medella               |   20200627 |        20200201 |
| nchs-mortality        |     202050 |          202005 |
| quidel                |   20200429 |        20200131 |
| quidel-covid-ag-test  |   20200729 |        20200724 |
| safegraph             |   20200620 |        20190101 |
| usa-facts             |   20200624 |        20200125 |
| youtube-survey        |   20200429 |        20200421 |
+-----------------------+------------+-----------------+
```

They should go in the header. Here's a correct example:
![image](https://user-images.githubusercontent.com/1158666/104052054-1ea61d00-51b7-11eb-9551-9fd16170a262.png)

Questions:
* Should this be per source, or per source and per signal?
* Should we also list the earliest available date (second column above; distinct from first issue)

**Comment by Akvannortwick** [comment]
@krivard I think we should do the earliest date as well. It helps clarify any misunderstanding. As for the first question... it might depend on how many signals per source maybe we should include the earliest date available only?

**Comment by krivard** [comment]
> we should do the earliest date as well

Agreed.

> it might depend on how many signals per source

Hmmm. Some of the sources have natural splits, each with their own header, so that's easy. Some of them don't though. Is it reasonable to add an extra column to the signal description tables, or will that be too busy?

**Comment by Akvannortwick** [comment]
> Hmmm. Some of the sources have natural splits, each with their own header, so that's easy. Some of them don't though. Is it reasonable to add an extra column to the signal description tables, or will that be too busy?


I don't think another column would be too busy if it's just the date. But the only way to really know would be to see it imo.

**Comment by krivard** [comment]
> the only way to really know would be to see it imo.

Agreed -- if you try it in a branch (use a placeholder date like 00-00-0000), then we can set up a demo environment.
