### ISSUE TITLE
covidcast: support querying all counties of a state

### ISSUE THREAD

**Issue by sgratzl** [cmu-delphi/delphi-epidata#380]
see also https://github.com/cmu-delphi/www-covidcast/issues/721

a simple workaround would be to support prefix querie: e.g., `geo_type = 'county' and geo_value like '06%'` would query all counties in California (06). 

with the upcoming Python version we could also have a simple mapping that supports the tree navigation from nation -> state -> county.

**Comment by krivard** [comment]
this is a good idea, though it does require storing a mapping from state codes to their numeric FIPS equivalents. that kind of thing will be much easier to build and test once we're in Flask, but if cmu-delphi/www-covidcast#721 needs the lift earlier than that we might be able to hack something together. There's a workaround using the R or Python clients that doesn't require typing in all the counties in a state by hand; I'll comment in the other thread.

**Comment by capnrefsmmat** [comment]
The first two digits of a five-digit FIPS are the state, so in principle you could do this with a numeric range or LIKE query on `geo_value` -- no mapping file needed

**Comment by krivard** [comment]
...how do you get from "ca" to "06" then?

**Comment by sgratzl** [comment]
Duplicate of #542
