### ISSUE TITLE
consider support for querying different geo_types at the same time

### ISSUE THREAD

**Issue by sgratzl** [cmu-delphi/delphi-epidata#389]
e.g., allow to query both the state CA and all its counties at the same time. 

possible notation: extent the logic of `geo_values` or add a new generic `geo` parameter to support a colon syntax, similar to the `signals` parameter within the covidcast_meta option. 

examples: 
 * `state:CA`
 * `state:*` or just `state`
 * `county:06002`
 * `county:06* if we wanna support a prefix syntax, see #380 
 * `state:CA,county:06*`

**Comment by krivard** [comment]
This is an excellent candidate improvement for after the Flask conversion -- we'll revisit it then.

**Comment by sgratzl** [comment]
mostly done beside the cross geo type mappings -> https://github.com/cmu-delphi/delphi-epidata/issues/542
