### ISSUE TITLE
add merged healthdata.gov signal that combines weekly and daily data

### ISSUE THREAD

**Issue by nickreich** [cmu-delphi/delphi-epidata#398]
Related to #288 ...
I understand that there is a new healthdata.gov signal in covidcast that uses the "weekly" timeseries file with hospitalization data posted by HHS. This is great. however, for modeling teams that wish to update their forecasts more than once a week, there are daily updates to these files that can be merged with the weekly file to create a single signal that is updated more frequently. We have cobbled something together in the [covidData package](https://github.com/reichlab/covidData), but don't feel that this is a stable or long-term solution or one that we (the COVID-19 Forecast Hub) want to maintain for general usability for other groups. The function that loads this data is in this file: https://github.com/reichlab/covidData/blob/master/R/healthdata_data.R

We would find it super helpful if similar functionality could be added to covidcast, namely a "merged" signal that combines the most recent weekly and daily reports from HHS and surfaces the same daily new hospitalization counts that are already being surfaced, just with more frequent updates. Thanks for considering!

**Comment by krivard** [comment]
Is that the same as #308? If so, I believe we're in final checks for that (in fact I think we've soft-launched and I was just waiting to verify this week's data before documenting it)

**Comment by nickreich** [comment]
yes! sorry. duplicate. will close.
