### ISSUE TITLE
Switch fb-survey documentation to show weighted signals by default

### ISSUE THREAD

**Issue by capnrefsmmat** [cmu-delphi/delphi-epidata#447]
Unless we have a good reason not to, we can switch the documentation to show the weighted signals by default in all the tables, and mention the existence of unweighted signals underneath where we currently mention weighted ones.

**Comment by krivard** [comment]
Just noting here that weighted signals nominally have an additional 1-2 days of lag, although I believe the 7-day averager masks that fact

**Comment by capnrefsmmat** [comment]
Our feeling at the survey standup is that for most users, 1-2 days of lag isn't important; most people would be looking for demographically representative data, and we can have a note explaining that unweighted signals are available if speed is important.
