### ISSUE TITLE
Unable to obtain data for all requested dates with issue "20210322" of covid_hosp endpoint 

### ISSUE THREAD

**Issue by e3bo** [cmu-delphi/delphi-epidata#466]
With this url:

https://delphi.cmu.edu/epidata/api.php?endpoint=covid_hosp&states=PA&dates=20200101-20210322&issues=20210322

I get the response:

`{"result":1,"epidata":[{"state":"PA","issue":20210322,"date":20210317,"critical_staffing_shortage_today_yes":17,"critical_staffing_shortage_today_no":202,"critical_staffing_shortage_today_not_reported":7,"critical_staffing_shortage_anticipated_within_week_yes":22,"critical_staffing_shortage_anticipated_within_week_no":197,"critical_staffing_shortage_anticipated_within_week_not_reported":7,"hospital_onset_covid":19,"hospital_onset_covid_coverage":220,"inpatient_beds":31460,"inpatient_beds_coverage":226,"inpatient_beds_used":23970,"inpatient_beds_used_coverage":226,"inpatient_beds_used_covid":1906,"inpatient_beds_used_covid_coverage":220,"previous_day_admission_adult_covid_confirmed":232,"previous_day_admission_adult_covid_confirmed_coverage":226,"previous_day_admission_adult_covid_suspected":376,"previous_day_admission_adult_covid_suspected_coverage":220,"previous_day_admission_pediatric_covid_confirmed":2,"previous_day_admission_pediatric_covid_confirmed_coverage":219,"previous_day_admission_pediatric_covid_suspected":21,"previous_day_admission_pediatric_covid_suspected_coverage":218,"staffed_adult_icu_bed_occupancy":2659,"staffed_adult_icu_bed_occupancy_coverage":226,"staffed_icu_adult_patients_confirmed_suspected_covid":389,"staffed_icu_adult_patients_confirmed_suspected_covid_coverage":220,"staffed_icu_adult_patients_confirmed_covid":353,"staffed_icu_adult_patients_confirmed_covid_coverage":226,"total_adult_patients_hosp_confirmed_suspected_covid":1870,"total_adult_patients_hosp_confirmed_suspected_covid_coverage":220,"total_adult_patients_hosp_confirmed_covid":1570,"total_adult_patients_hosp_confirmed_covid_coverage":226,"total_pediatric_patients_hosp_confirmed_suspected_covid":36,"total_pediatric_patients_hosp_confirmed_suspected_covid_coverage":219,"total_pediatric_patients_hosp_confirmed_covid":22,"total_pediatric_patients_hosp_confirmed_covid_coverage":219,"total_staffed_adult_icu_beds":3653,"total_staffed_adult_icu_beds_coverage":226,"inpatient_beds_utilization_coverage":226,"inpatient_beds_utilization_numerator":23970,"inpatient_beds_utilization_denominator":31460,"percent_of_inpatients_with_covid_coverage":220,"percent_of_inpatients_with_covid_numerator":1906,"percent_of_inpatients_with_covid_denominator":23754,"inpatient_bed_covid_utilization_coverage":220,"inpatient_bed_covid_utilization_numerator":1906,"inpatient_bed_covid_utilization_denominator":31083,"adult_icu_bed_covid_utilization_coverage":220,"adult_icu_bed_covid_utilization_numerator":389,"adult_icu_bed_covid_utilization_denominator":3548,"adult_icu_bed_utilization_coverage":226,"adult_icu_bed_utilization_numerator":2659,"adult_icu_bed_utilization_denominator":3653,"inpatient_beds_utilization":0.76191989828354,"percent_of_inpatients_with_covid":0.080239117622295,"inpatient_bed_covid_utilization":0.06131969243638,"adult_icu_bed_covid_utilization":0.10963923337091,"adult_icu_bed_utilization":0.72789488091979}],"message":"success"}`

With this url:

https://delphi.cmu.edu/epidata/api.php?endpoint=covid_hosp&states=PA&dates=20200101-20210306&issues=20210306

I get the response I expect, which has data for all dates in the requested range of Jan 1 2020 to March 6, 2021. Is there something wrong with my first url or my expectations?

**Comment by krivard** [comment]
Thank you for reporting the problem. I suspect one of the following is happening:
* the 20210322 issue was imported correctly but did not contain all dates (in which case, we should implement as_of logic)
* our copy of the 20210322 issue was corrupted due to a problem with the new healthdata.gov API
* our copy of the 20210322 issue was corrupted due to a problem with merging the timeseries and daily updates
* our copy of the 20210322 issue was corrupted due to some other problem

I'll be able to get more details on what's happening later today.

**Comment by e3bo** [comment]
Thanks! Issue 20210320 seems to be working and will meet my needs for the next few days.

**Comment by krivard** [comment]
Okay, looks like we have option 1: the 20210322 issue was imported correctly but did not contain all dates. 

20210322 happens to not be an issue of the state timeseries dataset, but instead an issue of the state daily dataset. State daily issues only include (and only ever included) one date. Other issues which share this behavior include 20210113, 20210128, 20210131, etc.; unfortunately we don't have an easy way to expose which issues are which at the moment.

I'm going to put adding as_of logic on our work schedule. In the meantime, I recommend the following:
* If data up to a week old is okay, fetch issues going backward in time until the number of dates covered is >1, and keep only the matching issue
* If you need data guaranteed to be less than 3 days old, fetch issues going backward in time until the number of dates covered is >1, then apply the diffs in chronological order [using something like this](https://github.com/cmu-delphi/delphi-epidata/blob/a28d336d98cf592dd7c114ca5bae7afc800531c4/src/acquisition/covid_hosp/state_daily/update.py#L70)

**Comment by e3bo** [comment]
Thanks for the fast response. The as_of support will be nice when it becomes available but I can certainly get by with the suggested alternatives for the time being.
