### ISSUE TITLE
[summer] Tune index hint crossover point to minimize query time for research use

### ISSUE THREAD

**Issue by krivard** [cmu-delphi/delphi-epidata#518]
Thanks to #516 we're now using an index hint which dramatically reduces query time for the large-timespan, <5-geo-values queries sent by the frontend. For research use however, people submit queries with arbitrary numbers of geo values, and we don't actually know how many geo values it takes before the `by_issue` index stops being the best performer.

Profile a bunch of sample queries to get a notion of how running time fluctuates with the number of distinct geo values, source-signal pairs, or timevalue pairs requested while using each index. Plot the results so it's easy to see which indexes perform best in which circumstances.

**Comment by TaraLakdawala** [comment]
When querying by county in the source jhu-csse for signal confirmed_cumulative_num, the following query times were graphed and a crossover point of ~150 geo_values was found

![county-149-jhucsse-source](https://user-images.githubusercontent.com/40361282/125330347-a27ec480-e314-11eb-8670-06f50f753af9.png)
![county-249-jhucsse-source](https://user-images.githubusercontent.com/40361282/125330348-a3175b00-e314-11eb-8b3b-cb89c5925692.png)

**Comment by krivard** [comment]
Index hints no longer relevant in v4
