### ISSUE TITLE
Add structured log statement for failed covidcast files

### ISSUE THREAD

**Issue by krivard** [cmu-delphi/delphi-epidata#526]
We currently log failed files from covidcast acquisition as:

```
handling  /common/covidcast/receiving/chng/20210227_state_smoothed_adj_outpatient_cli.csv
archiving as failed - chng
```

To make it possible to alert on these failed files, we need to put them into the structured log for easier processing by Elastic.

**Comment by melange396** [comment]
looks like this was done in #611
