### ISSUE TITLE
Broken link under combination indicator page

### ISSUE THREAD

**Issue by xindyhu** [cmu-delphi/delphi-epidata#531]
Hello,
The hyperlink under "Statistical Combination Signals (Inactive)" on this page is broken.
https://cmu-delphi.github.io/delphi-epidata/api/covidcast-signals/indicator-combination.html
We have been using the NMF combined indicator (nmf_day_doc_fbc_fbs_ght) since last October for a project. I understand you stopped updating this as of March this year but I would like to read more about this indicator and see if we can recreate it ourselves. 
Thanks!

**Comment by xindyhu** [comment]
@krivard Thanks so much, just emailed you from chu @ mathematica-mpr.com

**Comment by sgratzl** [comment]
all links seem to be working for me now -> closing
