### ISSUE TITLE
CMU Flu View data not updated last 2 weeks

### ISSUE THREAD

**Issue by blackjack940** [cmu-delphi/delphi-epidata#537]
We noticed that CMU flu view table hasn't been updated in the last couple of weeks but the CDC source table has updated data. The max(epiweek) available in the CMU dataset is 202115 whereas CDC has 202117. Can you please let me know when the table might be updated?

**Comment by krivard** [comment]
The logs have one failed data acquisition for FluView from this morning at 3 am, but no other failures from the past two weeks, which is quite odd. I'll dig a little deeper and check back.

**Comment by krivard** [comment]
?
```
$ curl -s "https://delphi.cmu.edu/epidata/api.php?endpoint=fluview_meta" |jq '.'
{
  "epidata": [
    {
      "latest_update": "2021-05-07",
      "latest_issue": 202117,
      "table_rows": 1267703
    }
  ],
  "result": 1,
  "message": "success"
}
```

**Comment by blackjack940** [comment]
The row counts have been same since 4/27 in the table. the CDC table has epiweek until 202117 whereas CMU table has 202115. is it possible to check if new data is being pulled in from CDC in the past 2 weeks?

**Comment by krivard** [comment]
```
MariaDB [epidata]> select count(1),issue,max(release_date) from fluview where issue>=202115 group by issue;
+----------+--------+-------------------+
| count(1) | issue  | max(release_date) |
+----------+--------+-------------------+
|     5913 | 202115 | 2021-04-25        |
|     5986 | 202116 | 2021-04-30        |
|     6059 | 202117 | 2021-05-07        |
+----------+--------+-------------------+
3 rows in set (0.03 sec)
```

Can you post more details about what query you're submitting and what you're getting back?

**Comment by blackjack940** [comment]
We are using the below url to download the API and we are getting only 3,650 rows for issue 202117. Is there an updated url that we can use? Using this URL, we have max(epiweek) = 202115 whereas CDC has epiweek = 202117. Please let me know if there is an updated URL that I need to use. 


https://api.covidcast.cmu.edu/epidata/api.php?source=fluview&regions=al,ak,az,ar,ca,co,ct,de,fl,ga,hi,id,il,in,ia,ks,ky,la,me,md,ma,mi,mn,ms,mo,mt,ne,nv,nh,nj,nm,,,ny_minus_jfk,nc,nd,oh,ok,or,pa,ri,sc,sd,tn,tx,ut,vt,va,wa,wv,wi,wy,as,mp,dc,gu,pr,vi,ord,lax,jfk,nat&epiweeks=202001-20290131

**Comment by krivard** [comment]
Two fixes. 

First, 20290131 is a day, not an epiweek; you probably want 202904. It also looks like there's a couple of empty region strings in your query (",,,") but that shouldn't cause any problems, it's just me being picky.

Second, you've run into the results limit, which is currently something like 3500 entries. That's about a year's worth of the state data you've selected, but you've asked for more than a year, so Epidata gives you as much as it can, but also returns an error code to let you know you didn't get everything you wanted. To avoid running into this by surprise,
1. make sure you check the `result` and `message` of the returned JSON
2. split large queries by time or region

```
# query as written, with s/20290131/202904/
$ curl -s "https://api.covidcast.cmu.edu/epidata/api.php?source=fluview&regions=al,ak,az,ar,ca,co,ct,de,fl,ga,hi,id,il,in,ia,ks,ky,la,me,md,ma,mi,mn,ms,mo,mt,ne,nv,nh,nj,nm,,,ny_minus_jfk,nc,nd,oh,ok,or,pa,ri,sc,sd,tn,tx,ut,vt,va,wa,wv,wi,wy,as,mp,dc,gu,pr,vi,ord,lax,jfk,nat&epiweeks=202001-202904" \
| jq '{message, result}'
{
  "message": "too many results, data truncated",
  "result": 2
}
# query reduced to just 2021
$ curl -s "https://api.covidcast.cmu.edu/epidata/api.php?source=fluview&regions=al,ak,az,ar,ca,co,ct,de,fl,ga,hi,id,il,in,ia,ks,ky,la,me,md,ma,mi,mn,ms,mo,mt,ne,nv,nh,nj,nm,,,ny_minus_jfk,nc,nd,oh,ok,or,pa,ri,sc,sd,tn,tx,ut,vt,va,wa,wv,wi,wy,as,mp,dc,gu,pr,vi,ord,lax,jfk,nat&epiweeks=202101-202120" \
| jq '.epidata|.[]|.epiweek' | grep -m1 202117 
202117
```

There's also a brand-new streaming API at a slightly different URL, which will give you back arbitrarily large numbers of results so you won't have to split your queries. It's still in beta, but you can try it if you promise to let us know if you run into any problems:

```
# query using new streaming endpoint, with s/20290131/202904/
$ curl -s "https://api.covidcast.cmu.edu/epidata/fluview/?regions=al,ak,az,ar,ca,co,ct,de,fl,ga,hi,id,il,in,ia,ks,ky,la,me,md,ma,mi,mn,ms,mo,mt,ne,nv,nh,nj,nm,,,ny_minus_jfk,nc,nd,oh,ok,or,pa,ri,sc,sd,tn,tx,ut,vt,va,wa,wv,wi,wy,as,mp,dc,gu,pr,vi,ord,lax,jfk,nat&epiweeks=202001-202904" \
| jq '.epidata|.[]|.epiweek' | grep -m1 202117
202117
```

**Comment by blackjack940** [comment]
Great. Thank you.
