### ISSUE TITLE
improve indicator dashboard indicator/signal names

### ISSUE THREAD

**Issue by sgratzl** [cmu-delphi/delphi-epidata#546]
coming from https://github.com/cmu-delphi/www-covidcast/pull/931#issuecomment-841533001:

> The indicator names should be more descriptive.

**Comment by krivard** [comment]
Yeah we need to figure out what the indicator status "items" actually represent -- they started out as "representative signal for this source" but that makes more sense for coverage data than for backfill profiles.

**Comment by sgratzl** [comment]
see also https://docs.google.com/document/d/1KVRezwvEPM2qG1nSolTiPXu6R_LoaF3YgG5en2glcM8/edit#

**Comment by sgratzl** [comment]
superseded by #559 -> closing
