### ISSUE TITLE
docs/clients: change to new auth method 

### ISSUE THREAD

**Issue by sgratzl** [cmu-delphi/delphi-epidata#549]
the new flask server version supports additional methods how the `auth` parameter is provided. All of them have the advantage that they are not longer part of the URL that less likely to be tracked by accident. 

e.g. the `Bearer` variants would be an easy one to change.

see also

https://github.com/cmu-delphi/delphi-epidata/blob/2fe7bc7026fa3a6cc683155262c60f46db5338fc/src/server/_validate.py#L8-L19

https://github.com/cmu-delphi/delphi-epidata/blob/2fe7bc7026fa3a6cc683155262c60f46db5338fc/tests/server/test_validate.py#L40-L57

**Comment by krivard** [comment]
@RoniRos is there a list somewhere of all the groups that have auth access to these datasets?

**Comment by sgratzl** [comment]
the old method will still work but the new one would be better

**Comment by RoniRos** [comment]
> @RoniRos is there a list somewhere of all the groups that have auth access to these datasets?

I'm sorry I'm not following.  Maybe we can talk about this during the tech leads meeting?

**Comment by melange396** [comment]
covered as part of api keys deployment
