### ISSUE TITLE
clients: move to the new endpoint logic

### ISSUE THREAD

**Issue by sgratzl** [cmu-delphi/delphi-epidata#563]
so away from `api.php?endpoint=xxx` to `/endpoint/`. 

- [x] JS
- [ ] R
- [x] Python

Note: this will also disable the compatibility layer of the server, i.e. it will always return an empty epidata array object.

**Comment by melange396** [comment]
maybe do this first to make #554 a tiny bit easier

**Comment by melange396** [comment]
python client is being addressed in #1285

**Comment by melange396** [comment]
The R client is effectively deprecated, so we can call this done
