### ISSUE TITLE
consider using sort(key=...) function

### ISSUE THREAD

**Issue by sgratzl** [cmu-delphi/delphi-epidata#573]
it looks quite difficult how the sorting is handled:

https://github.com/cmu-delphi/delphi-epidata/blob/d6dd046663d93e48792287a456cb7839547c4055/src/acquisition/covidcast/database.py#L330-L335

can't the key function as in `.sort(key=lambda x: (x['data_source'], x['signal'], x['time_type'], x['geo_type']))` be used instead?

**Comment by dshemetov** [comment]
@melange396 does this have to do something with threads? It seems like all the thread work is done before this chunk?

**Comment by melange396** [comment]
yeah, this is done post-threading (because the threaded workers arent likely to retain the original ordering).  `.sort(key=)` would be a much less ugly way to do this.

**Comment by nolangormley** [comment]
Looking into this. Seems like something we could clear up during the v4 integration.

**Comment by dshemetov** [comment]
To top that off, this meta computations code is getting rewritten in #947, which will go into #646, which in turn should be merged in after v4. It'll look something [like this](https://github.com/cmu-delphi/delphi-epidata/blob/392a0af6dab494ae88fd87513956369f953adeb2/src/acquisition/covidcast/database_meta.py#L429) when done.
