### ISSUE TITLE
Querying CHNG data is much slower than querying equivalent amounts of other data

### ISSUE THREAD

**Issue by capnrefsmmat** [cmu-delphi/delphi-epidata#579]
For example,

```r
> library(covidcast)
> system.time(covidcast_signal("chng", "smoothed_adj_outpatient_covid", "2020-04-15", "2020-06-19", geo_type="state"))
Fetched day 2020-04-15 to 2020-06-19: num_entries = 3564
   user  system elapsed 
  0.251   0.019   2.977 
> system.time(covidcast_signal("fb-survey", "smoothed_wcli", "2020-04-15", "2020-06-19", geo_type="state"))
Fetched day 2020-04-15 to 2020-06-19: num_entries = 3395
   user  system elapsed 
  0.197   0.006   0.734 
```

There are a similar number of rows received, but CHNG takes several times longer, and this seems consistent when I repeat the requests. Katie suggests there may be some bad index use happening, since CHNG has many more issues and hence more filtering to find the latest issue.

**Comment by capnrefsmmat** [comment]
This is extra-bad at the county level when specifying some geo_values (in this case, the 50 most populous counties):

https://api.covidcast.cmu.edu/epidata/api.php?source=covidcast&data_source=chng&signal=smoothed_adj_outpatient_cli&time_type=day&geo_type=county&time_values=20200415-20200625&geo_value=06037,17031,48201,04013,06073,06059,12086,48113,36047,06065,32003,36081,53033,06071,48439,48029,12011,06085,26163,06001,36061,25017,42101,06067,12099,36103,12057,36005,12095,36059,39049,48453,27053,26125,39035,42003,49035,06013,51059,37183,37119,13121,24031,04019,48085,06019,29189,12103,15003,36119

The response is actually truncated -- there's part of a JSON array and then it ends:

```
{ "epidata": [{"geo_value":"04013","signal":"smoothed_adj_outpatient_cli","time_value":20200415,"direction":null,"issue":20210221,"lag":312,"value":0.47389,"stderr":null,"sample_size":null},{"geo_value":"04019","signal":"smoothed_adj_outpatient_cli","time_value":20200415,"direction":null,"issue":20210221,"lag":312,"value":0.942942,"stderr":null,"sample_size":null},
...
{"geo_value":"37119","signal":"smoothed_adj_outpatient_cli","time_value":20200423,"direction":null,"issue":20210221,"lag":304,"value":1.31216,"stderr":null,"sample_size":null}
```

Notice there's no `]}` at the end to close out. The truncation seems to happen at 30 seconds, and in `&format=csv`, no data is returned and the connection is closed in a weird way, causing the R client to say:

```
Error in curl::curl_fetch_memory(url, handle = handle) : 
  HTTP/2 stream 0 was not closed cleanly: INTERNAL_ERROR (err 2)
```

This is preventing me from pulling Change data for the top 50 counties for a comparison plot we wanted to make.

**Comment by sgratzl** [comment]
AFAIK 30s is the default nginx reverse proxy timeout, see also https://delphi-org.slack.com/archives/CT7BUGPFC/p1619020024028000?thread_ts=1618511804.025400&cid=CT7BUGPFC 

might be needed:
```
  # timeout in 600sec = 10min
        proxy_connect_timeout       600;
        proxy_send_timeout          600;
        proxy_read_timeout          600;
        send_timeout                600;
```

**Comment by capnrefsmmat** [comment]
Normally we get a 502 Gateway Timeout though, right? This seems to just be truncating the result or dying without giving a response.

(Also, the query should just be faster)

**Comment by melange396** [comment]
part of the problem here was rooted in the v3 database structure.  all the sample queries used in this issue now finish for me in ~half a second.

the other part relates to webserver timeouts, which have since been generously increased.
