### ISSUE TITLE
Support epiweek ranges or provide informative errors in covidcast

### ISSUE THREAD

**Issue by brookslogan** [cmu-delphi/delphi-epidata#639]
Requesting a single week of data succeeds:

```
Epidata$covidcast("nchs-mortality","deaths_allcause_incidence_num","week","state",202101,"ca")
```

But these fail with internal server errors (500 codes):

```
## expected to produce data
Epidata$covidcast("nchs-mortality","deaths_allcause_incidence_num","week","state",Epidata$range(202101,202102),"ca")
Epidata$covidcast("nchs-mortality","deaths_allcause_incidence_num","week","state","202101-202102","ca")
## expected to produce better error messages
Epidata$covidcast("jhu-csse","confirmed_incidence_num","day","state",Epidata$range(202050,202101),"ca")
```

The printed output is:

```
{html_document}
<html>
[1] <head>\n<meta http-equiv="Content-Type" content="text/html; charset=UTF-8 ...
[2] <body>\n<h1>Internal Server Error</h1>\n<p>The server encountered an inte ...
```

(content for a 500 error, data.frame-ified).

Some potential resolutions:
(a) produce error message for all of these
(b) produce data for all but the last, and a more informative error message for the last

**Comment by brookslogan** [comment]
Update:
 - the first two lines now produce data as expected
 - the last line still produces nonstandard error output; the response has class `c("xml_document","xml_node")` and prints the following:
```
{html_document}
<html>
[1] <head>\n<meta http-equiv="Content-Type" content="text/html; charset=UTF-8 ...
[2] <body>\n<h1>Internal Server Error</h1>\n<p>The server encountered an inte ...
```

**Comment by krivard** [comment]
This feels like something we should already be checking for (making sure we get week values for a week type and day values for a day type) but we must not be surfacing the error correctly.

If you get stuck, @rzats will be around over CMU's break and can consult.

**Comment by dmytrotsko** [comment]
Looks like this issue is not relevant anymore:
![image](https://github.com/cmu-delphi/delphi-epidata/assets/29557449/2561edb4-694e-470f-9082-47da3be032ac)
@melange396

**Comment by melange396** [comment]
this issue is for the R client

**Comment by dmytrotsko** [comment]
> this issue is for the R client

Oh, I see. Ok, I will check R client as well

**Comment by dmytrotsko** [comment]
This is for R client
![image](https://github.com/cmu-delphi/delphi-epidata/assets/29557449/70cb44d5-d264-4ecb-b652-8c7b9670b28a)
