### ISSUE TITLE
Allergy Responses

### ISSUE THREAD

**Issue by Ron-Rabie** [cmu-delphi/delphi-epidata#65]
I am not certain of the self reporting parameters you use in this "data" gathering exercise.  Usually, if the data environment is not closely controlled - the very essence of self reporting - the data collected are between nearly useless and totally useless. Let's take Navajo and Apache Counties in Arizona in mid April.  We are in such a high pollen environment, we get pollen danger notifications on our smartphones.  This is mostly for the respiration challenged and the allergic but it is useful to all.  Symptoms include difficulty breathing, mild to severe sinus headaches, persistent dry cough, occasional mild fevers, etc.  Sound familiar?  How many of those people have responded with positive covid symptoms out of simple fear that their allergic response is covid 19?  What we need rather than more of this near useless "data" is massive nationwide testing.  Perhaps Zuckerberg could throw a billion or two at that problem.  Dr. Ronald L Rabie, Los Alamos National Laboratory, Retired.

**Comment by krivard** [comment]
Hi Ron-Rabie, this would indeed be a concern if self-reported data were the only signal we were measuring. The advantage of collecting many independent sources of data, including data reported by healthcare professionals and testing services, is that confounding factors such as allergy season can be much more easily addressed. As this does not seem to be an issue with the data API itself, I will close this issue, and encourage you to contact your local, county, state, and national representatives in support of increased testing.
