### ISSUE TITLE
use epidata client in covidcast integration tests

### ISSUE THREAD

**Issue by dfarrow0** [cmu-delphi/delphi-epidata#67]
the covidcast integration tests should use the epidata client now that it supports the covidcast endpoints

**Comment by krivard** [comment]
We want to change

https://github.com/cmu-delphi/delphi-epidata/blob/dev/integrations/server/test_covidcast.py#L27-L35

to use Epidata.covidcast(), the same/similar way https://github.com/cmu-delphi/delphi-epidata/blob/f949439f1103854eb7f36c5f13a70c9ce549ede4/integrations/server/test_fluview.py#L62 uses Epidata.fluview()

**Comment by krivard** [comment]
Source for the client: https://github.com/cmu-delphi/delphi-epidata/blob/dev/src/client/delphi_epidata.py
