### ISSUE TITLE
support more meta data information about the available options

### ISSUE THREAD

**Issue by sgratzl** [cmu-delphi/delphi-epidata#673]
> It would be really nice to have package members or functions that will say what {data_source,signals,locations,regions,geo_values,time_values,geo_type,time_type,issues,lag,hospital_pks,collection_weeks,publication_dates} it covers.

would mostly require a distinct SQL query for categorical data.

data_source, signals and their valid geo_types and time_type can be covered by /covidcast/meta

**Comment by melange396** [comment]
unclear
