### ISSUE TITLE
JHU Docs not listing all available geographic levels

### ISSUE THREAD

**Issue by sgratzl** [cmu-delphi/delphi-epidata#679]
The “available for” section here might need to be updated with ‘nation’ ‘hhs’

![image](https://user-images.githubusercontent.com/4129778/128881133-28d1e435-63ab-40aa-b95c-97dca89b4a42.png)

**Comment by krivard** [comment]
Confirmed list of geo levels available for JHU:

https://github.com/cmu-delphi/covidcast-indicators/blob/f50278bba514cfbe123ebbc97038df07d0d6d567/jhu/delphi_jhu/geo.py#L6
