### ISSUE TITLE
HHS prop Signals not showing up in Epidata meta

### ISSUE THREAD

**Issue by qx-teo** [cmu-delphi/delphi-epidata#700]
HHS has 8 signals in total that appear in [covidcast_meta](https://api.covidcast.cmu.edu/epidata/covidcast_meta/) (rows 1316 to 1339), but 4 of these (the ones that a proportion-based) don't seem to appear when searching via covidcast/meta. The 4 signals in particular and the links I'm trying to find them at are below:

1. [confirmed_admissions_covid_1d_prop](https://api.covidcast.cmu.edu/epidata/covidcast/meta?signal=hhs:confirmed_admissions_covid_1d_prop)
2. [confirmed_admissions_covid_1d_prop_7dav](https://api.covidcast.cmu.edu/epidata/covidcast/meta?signal=hhs:confirmed_admissions_covid_1d_prop_7dav)
3. [confirmed_suspected_admissions_covid_1d_prop](https://api.covidcast.cmu.edu/epidata/covidcast/meta?signal=hhs:confirmed_suspected_admissions_covid_1d_prop)
4. [confirmed_suspected_admissions_covid_1d_prop_7dav](https://api.covidcast.cmu.edu/epidata/covidcast/meta?signal=hhs:confirmed_suspected_admissions_covid_1d_prop_7dav)

[Here](https://api.covidcast.cmu.edu/epidata/covidcast/meta?signal=hhs:confirmed_admissions_covid_1d) is an example of a signal that works.

**Comment by qx-teo** [comment]
@sgratzl

**Comment by krivard** [comment]
nope, that's for me. I've added the rows to the meta sheet and am working on addressing this in https://github.com/cmu-delphi/delphi-epidata/pull/701
