### ISSUE TITLE
missing "smoothed_wothers_masked_public" signal description

### ISSUE THREAD

**Issue by sgratzl** [cmu-delphi/delphi-epidata#717]
as referenced in https://docs.google.com/document/d/1J36nedP6eufeRE3TbyT_BK-ofE5d18kLif2UmORkYDU/edit#

However, it doesn't seem to be defined in https://docs.google.com/spreadsheets/d/1zb7ItJzY5oq1n-2xtvnPBiJu2L3AqmCKubrLkKJZVHs/edit#gid=329338228

**Comment by krivard** [comment]
There are an alarming number of these so I've created a DRAFT sheet and delegated content to @nmdefries and @WichadaLMK. Once they have the information entered I'll merge it into the main sheet and deploy.

**Comment by nmdefries** [comment]
This has already been filled in in the spreadsheet
