### ISSUE TITLE
consider not overwriting ingested files

### ISSUE THREAD

**Issue by pedritom-amzn** [cmu-delphi/delphi-epidata#73]
**problem:** after ingestion of a `covidcast` file, the file is archived. if another file already exists in the archive with the same name, that file is overwritten, whether the ingestion succeeded or failed.

**impact:** while this may be acceptable for failed ingestions given the current logging, i am a little concerned about the potential silent overwrite in the case of success. for example, if you somehow get a truncated version of a file that was already ingested, having both versions archived could be useful for both determining the extent of the problem and for quickly back-filling the lost data.

**proposal:** perhaps consider adding a timestamp to archived successfully ingested files?

_Originally posted by @pedritom-amzn in https://github.com/cmu-delphi/delphi-epidata/pull/70_

**Comment by krivard** [comment]
Closing this -- I hear you, but with data versioning the storage requirements for the archive would be far too high. We've since developed other methods (archivediffer S3) for reconstructing previously acquired files, and while they're not perfect, they're adequate for now.
