### ISSUE TITLE
Is this API here the same that supports FB visualization?

### ISSUE THREAD

**Issue by berniefu** [cmu-delphi/delphi-epidata#74]
Hi there!

My name is Bin and I work for Verily Life Sciences. I graduated from CMU (SCS 2013) so I'm very glad to see the news today that Delphi and FB are working together on the self reported symptom survey map:
https://covid-survey.dataforgood.fb.com/

I have then played with the API listed here. My main question: Is this API the same as that supports the FB map? For example, this API only gives me a subset of the zipcode:
https://delphi.cmu.edu/epidata/api.php?source=covidcast&data_source=fb-survey&signal=cli&time_type=day&geo_type=county&time_values=20200406-20200410&geo_value=*

As an example, the result does not contain Denver area (80xxx).

Thanks in advance for your help!

**Comment by dfarrow0** [comment]
Hey fellow character!

This API surfaces the same data that's shown by that visualization. For `geo_type=county`, `geo_value` is a [FIPS 6-4 county code](https://en.wikipedia.org/wiki/FIPS_county_code), _which is distinct from zip code_.

See https://www2.census.gov/geo/docs/reference/codes/files/national_county.txt for a list of county codes. Find more info on [the census website](https://www.census.gov/library/reference/code-lists/ansi.html).

From the file above:
```
CO,08,031,Denver County,H6
```

Denver county has FIPS 6-4 code `08031`. So you could use the following link to get data in that county:

https://delphi.cmu.edu/epidata/api.php?source=covidcast&data_source=fb-survey&signal=cli&time_type=day&geo_type=county&time_values=20200401-20200420&geo_value=08031

**Comment by berniefu** [comment]
lol. Thanks David!

To confirm another detail, is the unit of the 'value' field percentage?
"value":1.83148395307
^
|
a.k.a. is this 1.83%?

**Comment by dfarrow0** [comment]
For this particular `data_source=fb-survey`, yes, the value is a percentage. In general, the unit depends on the data source.

**Comment by berniefu** [comment]
Reopen this again to confirm more details: I calculated the county level data from 4/1 to 4/20 (getting a mean from value and sample_size), and generated a tableau graph on my side. However, the data doesn't not quite look at the FB map (https://covid-survey.dataforgood.fb.com/):

<img width="1019" alt="Screen Shot 2020-04-21 at 1 37 30 PM" src="https://user-images.githubusercontent.com/4495400/79906614-5c6ad780-83d5-11ea-9e64-bc8fa55a4c57.png">

Could you please share more details about how the FB data is generated?

Specifically as an example, for FIPS 27137 (St Louis MN), there is only one data point in the time range:
https://delphi.cmu.edu/epidata/api.php?source=covidcast&data_source=fb-survey&signal=cli&time_type=day&geo_type=county&time_values=20200401-20200420&geo_value=27137

The value is 0.145, which is different from the FB data (0.77% at this moment).

Thanks!!

**Comment by dfarrow0** [comment]
I'm most familiar with the technical aspects of the API. I'm not as comfortable with questions on how this particular signal is generated.

@lcbrooks would you be able to answer this question?

**Comment by brookslogan** [comment]
Facebook's visualizer's county-level data is based on weekly estimates using the weighted version of the estimator.  It should be most similar to the smoothed_wcli & smoothed_wili signals.

**Comment by berniefu** [comment]
Thanks Brooks! There is a wili signal types for FB survey data:
https://github.com/cmu-delphi/delphi-epidata/blob/master/docs/api/covidcast.md
Is that what you meant? I also didn't find anything talking about the 'smoothed'.

**Comment by dfarrow0** [comment]
The docs were stale. I just updated them with current signal names, including "smoothed" versions.

Relatedly, the [`covidcast_meta`](https://cmu-delphi.github.io/delphi-epidata/api/covidcast_meta.html) endpoint will return the current set of signal names for each sensor (along with other info).
