### ISSUE TITLE
API can't actually serve its maximum row limit with as_of

### ISSUE THREAD

**Issue by capnrefsmmat** [cmu-delphi/delphi-epidata#762]
The new covidcast endpoint supports up to 1,000,000 rows per query. Using the [upcoming covidcast R package](https://github.com/cmu-delphi/covidcast/pull/571) that supports using the endpoint with the high row limit, I can issue queries that fail to finish:

```r
library(covidcast)
start_day <- "2020-04-15"
end_day <- "2021-04-15"
as_of_day <- "2021-06-01"

df_cases <- covidcast_signal("jhu-csse", "confirmed_7dav_incidence_prop",
                             start_day, end_day, as_of = as_of_day)
```

After 300 seconds (5 minutes exactly), this yields

```
Error in curl::curl_fetch_memory(url, handle = handle) : 
  HTTP/2 stream 0 was not closed cleanly: INTERNAL_ERROR (err 2)
```

With the `as_of` argument removed, we get complete results in 2 queries in 156 seconds.

With `as_of` present, it appears `end_day` can be somewhere between Dec 15, 2020 and Jan 15, 2021 before we hit 5 minutes for the query and it dies.

May be related to #579, though this seems specific to as_of, whereas 579 occurs without it.

**Comment by krivard** [comment]
There isn't an easy fix for this, because the time necessary to compute the query varies depending on the source and exact query parameters. 

@korlaxxalrok We probably need to do some benchmarking to figure out what the maximum transaction time is, then, what, double it and update the timeout to that value?

**Comment by capnrefsmmat** [comment]
From the perspective of the API clients, we need a row limit that will result in all queries being successful. If we publish the API client with a 1,000,000 row limit and some queries fail at that row limit, users will have no idea how to solve that problem and get the data.

So what's a conservative row limit to try that's better than the original 3,650? Maybe 100,000 instead of 1,000,000?

**Comment by krivard** [comment]
Changing the row limit would be an easy fix. Unfortunately, the row limit isn't the problem here. For example, this query returns only 248 results but requires 5876 seconds to compute:

```
SELECT t.geo_type, t.geo_value, t.source, t.signal, t.time_value, t.value FROM covidcast t WHERE ((t.source = 'jhu-csse' AND (t.signal = 'confirmed_7dav_incidence_prop' OR t.signal = 'deaths_7dav_incidence_prop'))) AND ((t.geo_type = 'state' AND (t.geo_value = 'al'))) AND ((t.time_type = 'day' AND (t.time_value BETWEEN 20210703 AND 20211103))) AND (t.is_latest_issue IS TRUE) ORDER BY t.geo_type ASC, t.geo_value ASC, t.source ASC, t.signal ASC, t.time_value ASC LIMIT 10000001;
```

That's why I'm recommending benchmarking. If we can figure out what kinds of queries are slow, then we can do things like:
* increase the timeout
* change what kinds of queries we let people submit (eg maybe an OR of two signals is no longer allowed)

**Comment by capnrefsmmat** [comment]
Maybe we should collect some examples of slow queries along with their `EXPLAIN` output, since that will give us an idea of what causes them to be slow and whether the fix should be client-side or server-side.

**Comment by capnrefsmmat** [comment]
For example, the [two indices](https://github.com/cmu-delphi/delphi-epidata/blob/962c3165f5ecf79ea962d543ab68911b76623ccb/src/ddl/covidcast.sql#L111-L112) on the covidcast table predate the `is_latest_issue` column, so the query above is likely doing a scan over all issues of those signals. That is likely also the case for the query in #579, and since CHNG has lots of re-issues, that would explain why it's much slower.

**Comment by krivard** [comment]
Essentially, MariaDB and InnoDB were not designed to handle this much data, and eliminating problems like these is one of the major benefits of all the improvements we're designing as part of the data warehouse project. In the meantime, index hints are a thing we already add in most cases, though it's definitely worth taking another pass through the API code to see where we've missed adding them.

**Comment by capnrefsmmat** [comment]
Yes, I understand; my point is that index hints won't help if `is_latest_issue` is not part of the most relevant indices.

**Comment by krivard** [comment]
Now that v4 has launched, the quoted query runs for me in 4m40s. This suggests we could move forward with changes to covidcastR.

However, I will note that in benchmark tests, v4 performed _worse_ than v3 for history queries (including as-of queries) in almost every conceivable way:

| Test | v3 | v4 |
| - | - | - |
| Total running time for benchmark dataset | 9m | 19m |
| Max running time | 17s | 16s |
| % queries under 10ms | 65% | 52% |
| % queries over 1s | 0.00036% | 1.1% |
| % queries slower than v3 | - | 86% |

Running times in prod are longer than on the isolated benchmark system, but the relative improvement/degradation should be sound, and we should generally expect as-of queries in v4 to be slower.

The NewRelic logs put the max transaction time in the last 7 days at 7m20s, which probably means we fixed the timeout problem -- @korlaxxalrok do you recall if we boosted the timeouts for v4?

**Comment by korlaxxalrok** [comment]
We did increase client and server timeouts in HAProxy, but we wouldn't have been using HAProxy when this issue was first noted.

**Comment by capnrefsmmat** [comment]
After merging https://github.com/cmu-delphi/covidcast/pull/571 so the package uses range queries instead of enumerating all dates, I tested the same query:

```
> start_day <- "2020-04-15"
> end_day <- "2021-04-15"
> as_of_day <- "2021-06-01"
> system.time(df_cases <- covidcast_signal("jhu-csse", "confirmed_7dav_incidence_prop",
+                              start_day, end_day, as_of = as_of_day))
Fetched day 2020-04-15 to 2021-02-13: num_entries = 998537
Fetched day 2021-02-14 to 2021-04-15: num_entries = 196628
   user  system elapsed 
 11.134   0.773 266.607 
```

I wouldn't call that *fast*, but it doesn't time out. I think we can close this and move forward with the updated R package.
