### ISSUE TITLE
Update COVID-19 Hospitalization by State documentation

### ISSUE THREAD

**Issue by ryantibs** [cmu-delphi/delphi-epidata#796]
The COVID-19 Hospitalization by State documentation says that updates are roughly weekly. See the last bullet point [here](https://cmu-delphi.github.io/delphi-epidata/api/covid_hosp.html#metadata).

My understanding is that we have been able to find a way to get updates daily. We should update the documentation.

**Comment by krivard** [comment]
We probably just need to drop this sentence: "New issues are expected to be released roughly weekly."

We already say in the header that we pull data from two healthdata.gov datasets to improve the frequency of updates:
* COVID-19 Reported Patient Impact and Hospital Capacity by State Timeseries (this is published weekly)
* COVID-19 Reported Patient Impact and Hospital Capacity by State (this is published on an irregular schedule, between every 1-6 days)

**Comment by ryantibs** [comment]
Sounds good (about dropping that sentence).

I'm confused about the regularity of update (is it really that irregular?). In recent times it has "felt" like it was regular, from my own use of the dashboard.

**Comment by ryantibs** [comment]
This probably doesn't belong here (on this issue), but I'm answering my own question, and recording here for now. Will be important for us to discuss at team leads shortly.

This is what I get for lag over time (at the national level).

```
library(covidcast)
library(ggplot2)

x = seq(as.Date("2020-09-01"), as.Date("2022-01-06"), by = "day")
y = sapply(x, function(date) date - max(
  covidcast_signal(
    "hhs", 
    "confirmed_admissions_covid_1d", 
    geo_type = "nation", 
    start = date - 10, 
    as_of = date)$time_value))
df = data.frame(x, y)
ggplot2::ggplot(df, aes(x = x, y = y)) + 
  geom_point() + 
  scale_x_date(breaks = "1 month", labels = "%b")
```

<img width="1258" alt="Screen Shot 2022-01-06 at 1 47 30 PM" src="https://user-images.githubusercontent.com/732541/148434920-36e555fc-4723-4371-8259-067b97f3eac0.png">

So it's been regular at around 2 days for a long stretch, apart from a few recent hiccups, and irregular before that.

**Comment by krivard** [comment]
I'd be fine with us saying that updates are "typically daily", however there seems to be an active problem with the dataset starting January 2. This is [their visualization tool](https://healthdata.gov/d/4cnb-m4rz/visualization), showing "Days since update" somehow getting larger and larger even though there are daily (and sometimes multiple times daily) updates since then:

![image](https://user-images.githubusercontent.com/1158666/148436580-d8e1a9f4-7469-4607-bd30-a10fab14f50b.png)
