### ISSUE TITLE
Fix bad table formatting in documentation

### ISSUE THREAD

**Issue by ryantibs** [cmu-delphi/delphi-epidata#798]
A lot of the tables in the Epidata documentation for the COVIDcast endpoint are badly formatted. (They may also be badly formatted in other places in the Epidata documentation, I haven't looked as carefully.)

For example, looking at the HHS data source this is what I see: 

![Screen Shot 2022-01-06 at 12 09 13 PM](https://user-images.githubusercontent.com/732541/148424295-130d4017-aba9-4ceb-820b-5d524650bead.png)

And when I scroll right, I get this: 

![Screen Shot 2022-01-06 at 12 09 06 PM](https://user-images.githubusercontent.com/732541/148424343-ec3be314-c809-4c0f-912d-472e6586a6c3.png)

We should fix this.

**Comment by krivard** [comment]
We have a volunteer who will be picking this up as an onboarding activity. Reference links:
* [rendered page for the above](https://cmu-delphi.github.io/delphi-epidata/api/covidcast-signals/hhs.html)
* [source for the above](https://github.com/cmu-delphi/delphi-epidata/blob/dev/docs/api/covidcast-signals/hhs.md)

More about markdown formatting:
* [Markdown for Jekyll](https://www.markdownguide.org/tools/jekyll/)
* [User Guide for Just the Docs](https://just-the-docs.github.io/just-the-docs/docs/ui-components), the theme we use

NB you won't need to know how to run Jekyll or Just The Docs yourself; our GitHub CI system does that for you. If you fork the repository you'll be able to set up your own Pages site for previewing your changes before you open a pull request. The configuration settings you'll need should look something like this:

![image](https://user-images.githubusercontent.com/1158666/179788109-0e91f465-9057-49d2-9da6-3ef0aaeeaf29.png)
