### ISSUE TITLE
Unify Change data source

### ISSUE THREAD

**Issue by ryantibs** [cmu-delphi/delphi-epidata#800]
On the export data tool, we show "Change Healthcare (COVID Like Illness)" and "Change Healthcare (Confirmed COVID)" as separate data sources. But they're not ... can we please unify into a single "Change Healthcare" data source.

I assume this is a matter of just changing something in some spreadsheet somewhere ...

By the way, wherever we use "COVID-Like Illness" we should make sure to hyphenate the first two words.

**Comment by krivard** [comment]
We introduced an extra layer of categorization on purpose in June 2021 to distinguish groups within a source that may differ in:
* geographic coverage
* update cadence
* lag pattern
* backfill pattern

I do agree that COVID and CLI are probably similar enough that they're not worth separating, and I will make that change.

I expect however that outpatient and inpatient signals within CHNG will differ and should thus be grouped separately. Thoughts?

**Comment by ryantibs** [comment]
Thanks.  

I think separating it into "Change Healthcare (Inpatient)", and "Change Healthcare (Outpatient)" is fine.  If nothing else, because it also mirrors what we have in "Doctors Visits from Claims" and "Hospital Admissions from Claims".
