### ISSUE TITLE
Documentation of regions for kcdc_ili and ecdc_ili.

### ISSUE THREAD

**Issue by mpanaggio** [cmu-delphi/delphi-epidata#852]
The api for accessing kcdc_ili and ecdc_ili data requires listing regions.  However, the documentation does not provide a list of regions where data is available.  It would be helpful to add that information to the documentation.

**Comment by krivard** [comment]
@LeonLu2 I'll get you database credentials and some pointers to how to dig the region list out of the database. [From the source code](https://github.com/cmu-delphi/delphi-epidata/blob/3f0ff0f867188035e5369f6d03e78cdbe2872166/src/acquisition/kcdc/kcdc_update.py#L139), it looks like the region is hard-coded to always be `ROK`, but we should confirm that in the actual data.

[Source for KCDC ILI endpoint docs](https://github.com/cmu-delphi/delphi-epidata/blob/dev/docs/api/kcdc_ili.md)
