### ISSUE TITLE
Revert CI config after Epidata v4 migration is complete

### ISSUE THREAD

**Issue by korlaxxalrok** [cmu-delphi/delphi-epidata#869]
https://github.com/cmu-delphi/delphi-epidata/blob/977c8336fdcf4cd070be345d971a5b319836270d/.github/workflows/ci.yaml#L111

**Comment by korlaxxalrok** [comment]
We need to temporarily build containers from ` v4-schema-revisions-release-prep`. This is a reminder to revert that change at some point.

**Comment by melange396** [comment]
Also, after v3 is no longer running, we can remove the [SQLALCHEMY_ENGINE_OPTIONS line](https://github.com/cmu-delphi/delphi-ansible-web/blob/main/vars.yml#L68) from `cmu-delphi/delphi-ansible-web:vars.yml`, or at least remove the only configuration entry in it.  It has been superceeded by [defaults in `cmu-delphi/delphi-epidata`](https://github.com/cmu-delphi/delphi-epidata/commit/9e57796796fa25c3b2bbf3ed792cd577eecc7839)

**Comment by melange396** [comment]
you may want also to close https://github.com/cmu-delphi/delphi-epidata/pull/916 whenever youre done with this issue

**Comment by krivard** [comment]
Fixed in #978
