### ISSUE TITLE
CHNG documentation should indicate sample size is not provided

### ISSUE THREAD

**Issue by capnrefsmmat** [cmu-delphi/delphi-epidata#910]
The CHNG documentation (and documentation for any other source with suppressed sample size) should document that the `sample_size` column is left deliberately blank, and give whatever reason we can share for that.

**Comment by krivard** [comment]
@LeonLu2 these are all covidcast signals, so you know where to find the documentation sources for them already.

Match disclaimer and reason with doctor visits: "Standard errors and sample sizes are not available for this data source."

- [ ] CHNG
- [ ] Hospital Admissions
- [ ] Google Search Trends

Disclaimer and reason: "Standard errors and sample sizes are not applicable to these metrics."

- [ ] Data Strategy and Execution Workgroup (DSEW)
- [ ] JHU
- [ ] USAFacts
- [ ] Department of Health and Human Services (HHS)
- [ ] NCHS Mortality

**Comment by krivard** [comment]
Fixed in #961
