### ISSUE TITLE
[Refactor] `insert_or_update_bulk` is a thin wrapper around `insert_or_update_batch` without a purpose?

### ISSUE THREAD

**Issue by dshemetov** [cmu-delphi/delphi-epidata#926]
in `src/acquisition/covidcast/database.py` we have:

```py
  def insert_or_update_bulk(self, cc_rows):
    return self.insert_or_update_batch(cc_rows)
```

minor nit: this wrapper doesn't seem to do anything...

_Originally posted by @dshemetov in https://github.com/cmu-delphi/delphi-epidata/pull/903#discussion_r883791096_

**Comment by dshemetov** [comment]
@krivard @melange396 thoughts? feels like a legacy wrapper that used to do something, but eventually became paper thin

**Comment by xavier-xia-99** [comment]
It does seem like it. I just tested doing away without the `insert_or_update_bulk `and using batch only and it seems to be working normally. The original version with `insert_or_update_batch` was called with the same argument (covidcast rows); the rest are all default arguments.

**Comment by melange396** [comment]
oh..  it looks like #948 might have done this but i cant make sense of the mass of changes in there.  ill give the assignment to @xavier-xia-99

**Comment by melange396** [comment]
whoops, duplicated in #989 -- im going to close this one as that one has a larger scope now
