### ISSUE TITLE
v4: insert_batch should fail if you try to run it with something already in signal_load

### ISSUE THREAD

**Issue by krivard** [cmu-delphi/delphi-epidata#941]
[We recently repaired the mergedkey branch of v4 to force it to run dbjobs automatically after insert_batch](https://github.com/cmu-delphi/delphi-epidata/pull/940). This is because [the fix_islatest query](https://github.com/cmu-delphi/delphi-epidata/blob/fbf878e70d3f4756fc3b7289f980799f7e06f0d4/src/acquisition/covidcast/database.py#L153-L163), having been stripped of the process_status column, performs quite poorly when you wait to run dbjobs until all the CSVs have been run through insert_batch. Each additional CSV file added to signal_load increases the number of rows participating in the fix_islatest join, but a smaller and smaller percentage of rows are updated.

We want to:
* Add a check to insert_batch so that if signal_load has anything in it, it throws an exception
* Add a test (could be an integration test if you did the database setup, or a unit test if you mocked out the database responses) to confirm that insert_batch throws an exception if you run it with something in signal_load

**Comment by melange396** [comment]
i have a call to `logger.fatal` [here](https://github.com/cmu-delphi/delphi-epidata/blob/1fe5b9c88cc315e9c6b60c0491dc48ca7e31dce4/src/acquisition/covidcast/database.py#L176) which i somehow boneheadedly thought would actually halt execution.  this needs to raise an exception at the very least.  it looks like @xavier-xia-99 might have gotten this done in #948 but i cant make sense of the mass of changes in there...  this should be included in v4 before it goes live, so ill get to adding the exception shortly.

**Comment by krivard** [comment]
Fixed in #967
