### ISSUE TITLE
Refactor usage of mock in `csv_to_database.py`

### ISSUE THREAD

**Issue by dshemetov** [cmu-delphi/delphi-epidata#966]
There's a needlessly complicated [mocking pattern in `csv_to_database.py`](https://github.com/cmu-delphi/delphi-epidata/blob/95d69dde75ed6b669e6af882ce0df3d82d9931c2/tests/acquisition/covidcast/test_csv_to_database.py#L74-L88). I think we can get rid of a lot of this and simplify the acquisition interface. 

I did a similar kind of refactor in #949, see the section "Further Details" for info.

**Comment by BrainIsDead** [comment]
@dshemetov  possibly it's already done [https://github.com/cmu-delphi/delphi-epidata/blob/beeb737b32fafa8efd4d494d79d6f725f5569b8b/tests/acquisition/covidcast/test_csv_to_database.py#L82](https://github.com/cmu-delphi/delphi-epidata/blob/beeb737b32fafa8efd4d494d79d6f725f5569b8b/tests/acquisition/covidcast/test_csv_to_database.py#L82)

**Comment by dshemetov** [comment]
I think you're right, I did that in the follow up #1072
